"""Generate dbt Silver models (clean + anomaly pair per table) from the
Bronze column list + silver_schema type rules. Re-run whenever types change.

Output: transform/models/silver/{dim,fact}_*.sql (+ __anomalies.sql)
        transform/models/silver/_silver.yml
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ingestion.config import REPO_ROOT
from ingestion.silver_schema import silver_model_name, silver_tables, silver_type
from ingestion.tpcds_schema import PRIMARY_KEYS, TABLES

SILVER_DIR = REPO_ROOT / "transform" / "models" / "silver"

# Regexes used to validate Bronze TEXT values before casting.
_INT_REGEX = r"^-?\d+$"
_NUM_REGEX = r"^-?\d+(\.\d+)?$"
_DATE_REGEX = r"^\d{4}-\d{2}-\d{2}$"


def _validation_expr(column: str, ptype: str) -> str | None:
    """Return a SQL expression that yields an anomaly string when column is bad,
    or NULL when column is acceptable (valid or NULL)."""
    if ptype == "integer":
        regex = _INT_REGEX
    elif ptype == "date":
        regex = _DATE_REGEX
    elif ptype.startswith("numeric"):
        regex = _NUM_REGEX
    else:
        return None
    return (
        f"case when {column} is not null and {column} !~ '{regex}' "
        f"then '{column}:not_{ptype.split('(')[0]}' end"
    )


def _cast_expr(column: str, ptype: str) -> str:
    """Safe-cast for Silver clean model. CASE guard is intentional: Postgres
    computes the WHERE-filter CTE and projection in a single pass when the
    expressions match, avoiding per-row repeat evaluation."""
    if ptype == "text":
        return f"nullif(trim({column}), '') as {column}"
    if ptype == "integer":
        return (
            f"case when {column} is null or {column} ~ '{_INT_REGEX}' "
            f"then {column}::integer end as {column}"
        )
    if ptype == "date":
        return (
            f"case when {column} is null or {column} ~ '{_DATE_REGEX}' "
            f"then {column}::date end as {column}"
        )
    if ptype.startswith("numeric"):
        return (
            f"case when {column} is null or {column} ~ '{_NUM_REGEX}' "
            f"then {column}::{ptype} end as {column}"
        )
    raise ValueError(f"unknown type: {ptype}")


def _validation_cte_sql(typed: list[tuple[str, str, str]]) -> str:
    """Build the validated CTE that flags each row with an _anomaly_reasons array."""
    if not typed:
        return "select raw.*, ARRAY[]::text[] as _anomaly_reasons from raw"
    tag_lines = [
        f"      case when {col} is not null and {col} !~ '{regex}' "
        f"then '{col}:not_{ptype.split('(')[0]}' end"
        for col, ptype, regex in typed
    ]
    return (
        "select\n"
        "    raw.*,\n"
        "    array_remove(array[\n"
        + ",\n".join(tag_lines) + "\n"
        + "    ], null) as _anomaly_reasons\n"
        + "  from raw"
    )


_HEADER = "-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.\n"


def _typed_columns(table: str, columns: list[str]) -> list[tuple[str, str, str]]:
    """Return [(column, ptype, regex), ...] for columns that need validation."""
    typed = []
    for c in columns:
        t = silver_type(table, c)
        if t == "integer":
            typed.append((c, t, _INT_REGEX))
        elif t == "date":
            typed.append((c, t, _DATE_REGEX))
        elif t.startswith("numeric"):
            typed.append((c, t, _NUM_REGEX))
    return typed


def _post_hook_for_pk(table: str, model_name: str) -> str | None:
    # Silver dim PK indexes are not worth the per-run create cost for this
    # workload — marts aggregate through int_sales_unified / int_returns_unified
    # rather than point-querying silver dims. dbt's unique test already catches
    # uniqueness violations. Leaving this as a no-op; re-enable if ad-hoc
    # silver dim queries become common.
    return None


def _clean_model_sql(table: str, columns: list[str]) -> str:
    """Clean model: flagged CTE with anomaly_reasons array, then filter where
    array is empty. Postgres folds this efficiently when the SELECT and CTE
    share predicates."""
    typed = _typed_columns(table, columns)
    cast_lines = [_cast_expr(c, silver_type(table, c)) for c in columns]
    casts_sql = ",\n    ".join(cast_lines)
    model_name = silver_model_name(table)
    config_args = "materialized='table', schema='silver'"
    post_hook = _post_hook_for_pk(table, model_name)
    if post_hook:
        config_args += f", post_hook=[\"{post_hook}\"]"

    sql = _HEADER + "{{ config(" + config_args + ") }}\n\n"
    sql += f"with raw as (\n  select * from {{{{ source('bronze', '{table}') }}}}\n),\n"
    sql += "validated as (\n  "
    sql += _validation_cte_sql(typed) + "\n)\n"
    sql += "select\n    " + casts_sql + "\n"
    sql += "from validated\n"
    sql += "where array_length(_anomaly_reasons, 1) is null\n"
    return sql


def _anomalies_model_sql(table: str, columns: list[str]) -> str:
    """Anomaly model: same flagged CTE, filtered to bad rows."""
    typed = _typed_columns(table, columns)
    if not typed:
        return (
            _HEADER
            + "{{ config(materialized='table', schema='silver') }}\n\n"
            + f"-- {table} has no type-cast columns; anomaly set is always empty.\n"
            + f"select *, array[]::text[] as anomaly_reasons\n"
            + f"from {{{{ source('bronze', '{table}') }}}}\n"
            + "where false\n"
        )
    columns_sql = ",\n    ".join(columns)
    sql = _HEADER + "{{ config(materialized='table', schema='silver') }}\n\n"
    sql += f"with raw as (\n  select * from {{{{ source('bronze', '{table}') }}}}\n),\n"
    sql += "validated as (\n  "
    sql += _validation_cte_sql(typed) + "\n)\n"
    sql += "select\n    " + columns_sql + ",\n"
    sql += "    _anomaly_reasons as anomaly_reasons\n"
    sql += "from validated\n"
    sql += "where array_length(_anomaly_reasons, 1) >= 1\n"
    return sql


def _schema_yml(models: list[tuple[str, str]]) -> str:
    """models is list of (model_name, pk_or_None)."""
    lines = ["# GENERATED by scripts/generate_silver_models.py", "version: 2", "", "models:"]
    for name, pk in models:
        lines.append(f"  - name: {name}")
        if pk:
            lines.append("    columns:")
            lines.append(f"      - name: {pk}")
            lines.append("        data_tests:")
            lines.append("          - not_null")
            lines.append("          - unique")
    return "\n".join(lines) + "\n"


def main() -> int:
    SILVER_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe only generated files (prefixes dim_, fact_)
    for f in SILVER_DIR.glob("dim_*.sql"):
        f.unlink()
    for f in SILVER_DIR.glob("fact_*.sql"):
        f.unlink()

    model_index: list[tuple[str, str | None]] = []
    for table in silver_tables():
        _, columns = TABLES[table]
        name = silver_model_name(table)
        (SILVER_DIR / f"{name}.sql").write_text(_clean_model_sql(table, columns))
        (SILVER_DIR / f"{name}__anomalies.sql").write_text(
            _anomalies_model_sql(table, columns)
        )
        pk = PRIMARY_KEYS.get(table)
        model_index.append((name, pk))
    (SILVER_DIR / "_silver.yml").write_text(_schema_yml(model_index))
    print(
        f"Generated {len(model_index)} Silver models (+ anomaly pairs) in {SILVER_DIR}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
