-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'store') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when s_store_sk is not null and s_store_sk !~ '^-?\d+$' then 's_store_sk:not_integer' end,
      case when s_rec_start_date is not null and s_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 's_rec_start_date:not_date' end,
      case when s_rec_end_date is not null and s_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 's_rec_end_date:not_date' end,
      case when s_closed_date_sk is not null and s_closed_date_sk !~ '^-?\d+$' then 's_closed_date_sk:not_integer' end,
      case when s_number_employees is not null and s_number_employees !~ '^-?\d+$' then 's_number_employees:not_integer' end,
      case when s_floor_space is not null and s_floor_space !~ '^-?\d+$' then 's_floor_space:not_integer' end,
      case when s_market_id is not null and s_market_id !~ '^-?\d+$' then 's_market_id:not_integer' end,
      case when s_division_id is not null and s_division_id !~ '^-?\d+$' then 's_division_id:not_integer' end,
      case when s_company_id is not null and s_company_id !~ '^-?\d+$' then 's_company_id:not_integer' end,
      case when s_gmt_offset is not null and s_gmt_offset !~ '^-?\d+(\.\d+)?$' then 's_gmt_offset:not_numeric' end,
      case when s_tax_precentage is not null and s_tax_precentage !~ '^-?\d+(\.\d+)?$' then 's_tax_precentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    s_store_sk,
    s_store_id,
    s_rec_start_date,
    s_rec_end_date,
    s_closed_date_sk,
    s_store_name,
    s_number_employees,
    s_floor_space,
    s_hours,
    s_manager,
    s_market_id,
    s_geography_class,
    s_market_desc,
    s_market_manager,
    s_division_id,
    s_division_name,
    s_company_id,
    s_company_name,
    s_street_number,
    s_street_name,
    s_street_type,
    s_suite_number,
    s_city,
    s_county,
    s_state,
    s_zip,
    s_country,
    s_gmt_offset,
    s_tax_precentage,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
