-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'call_center') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cc_call_center_sk is not null and cc_call_center_sk !~ '^-?\d+$' then 'cc_call_center_sk:not_integer' end,
      case when cc_rec_start_date is not null and cc_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'cc_rec_start_date:not_date' end,
      case when cc_rec_end_date is not null and cc_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'cc_rec_end_date:not_date' end,
      case when cc_closed_date_sk is not null and cc_closed_date_sk !~ '^-?\d+$' then 'cc_closed_date_sk:not_integer' end,
      case when cc_open_date_sk is not null and cc_open_date_sk !~ '^-?\d+$' then 'cc_open_date_sk:not_integer' end,
      case when cc_employees is not null and cc_employees !~ '^-?\d+$' then 'cc_employees:not_integer' end,
      case when cc_sq_ft is not null and cc_sq_ft !~ '^-?\d+$' then 'cc_sq_ft:not_integer' end,
      case when cc_mkt_id is not null and cc_mkt_id !~ '^-?\d+$' then 'cc_mkt_id:not_integer' end,
      case when cc_division is not null and cc_division !~ '^-?\d+$' then 'cc_division:not_integer' end,
      case when cc_company is not null and cc_company !~ '^-?\d+$' then 'cc_company:not_integer' end,
      case when cc_gmt_offset is not null and cc_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'cc_gmt_offset:not_numeric' end,
      case when cc_tax_percentage is not null and cc_tax_percentage !~ '^-?\d+(\.\d+)?$' then 'cc_tax_percentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when cc_call_center_sk is null or cc_call_center_sk ~ '^-?\d+$' then cc_call_center_sk::integer end as cc_call_center_sk,
    nullif(trim(cc_call_center_id), '') as cc_call_center_id,
    case when cc_rec_start_date is null or cc_rec_start_date ~ '^\d{4}-\d{2}-\d{2}$' then cc_rec_start_date::date end as cc_rec_start_date,
    case when cc_rec_end_date is null or cc_rec_end_date ~ '^\d{4}-\d{2}-\d{2}$' then cc_rec_end_date::date end as cc_rec_end_date,
    case when cc_closed_date_sk is null or cc_closed_date_sk ~ '^-?\d+$' then cc_closed_date_sk::integer end as cc_closed_date_sk,
    case when cc_open_date_sk is null or cc_open_date_sk ~ '^-?\d+$' then cc_open_date_sk::integer end as cc_open_date_sk,
    nullif(trim(cc_name), '') as cc_name,
    nullif(trim(cc_class), '') as cc_class,
    case when cc_employees is null or cc_employees ~ '^-?\d+$' then cc_employees::integer end as cc_employees,
    case when cc_sq_ft is null or cc_sq_ft ~ '^-?\d+$' then cc_sq_ft::integer end as cc_sq_ft,
    nullif(trim(cc_hours), '') as cc_hours,
    nullif(trim(cc_manager), '') as cc_manager,
    case when cc_mkt_id is null or cc_mkt_id ~ '^-?\d+$' then cc_mkt_id::integer end as cc_mkt_id,
    nullif(trim(cc_mkt_class), '') as cc_mkt_class,
    nullif(trim(cc_mkt_desc), '') as cc_mkt_desc,
    nullif(trim(cc_market_manager), '') as cc_market_manager,
    case when cc_division is null or cc_division ~ '^-?\d+$' then cc_division::integer end as cc_division,
    nullif(trim(cc_division_name), '') as cc_division_name,
    case when cc_company is null or cc_company ~ '^-?\d+$' then cc_company::integer end as cc_company,
    nullif(trim(cc_company_name), '') as cc_company_name,
    nullif(trim(cc_street_number), '') as cc_street_number,
    nullif(trim(cc_street_name), '') as cc_street_name,
    nullif(trim(cc_street_type), '') as cc_street_type,
    nullif(trim(cc_suite_number), '') as cc_suite_number,
    nullif(trim(cc_city), '') as cc_city,
    nullif(trim(cc_county), '') as cc_county,
    nullif(trim(cc_state), '') as cc_state,
    nullif(trim(cc_zip), '') as cc_zip,
    nullif(trim(cc_country), '') as cc_country,
    case when cc_gmt_offset is null or cc_gmt_offset ~ '^-?\d+(\.\d+)?$' then cc_gmt_offset::numeric(7,2) end as cc_gmt_offset,
    case when cc_tax_percentage is null or cc_tax_percentage ~ '^-?\d+(\.\d+)?$' then cc_tax_percentage::numeric(7,2) end as cc_tax_percentage
from validated
where array_length(_anomaly_reasons, 1) is null
