-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'call_center') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cc_call_center_sk is not null and cc_call_center_sk !~ '^-?\d+$' then 'cc_call_center_sk:not_integer' end,
      case when cc_rec_start_date is not null and cc_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'cc_rec_start_date:not_date' end,
      case when cc_rec_end_date is not null and cc_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'cc_rec_end_date:not_date' end,
      case when cc_closed_date_sk is not null and cc_closed_date_sk !~ '^-?\d+$' then 'cc_closed_date_sk:not_integer' end,
      case when cc_open_date_sk is not null and cc_open_date_sk !~ '^-?\d+$' then 'cc_open_date_sk:not_integer' end,
      case when cc_employees is not null and cc_employees !~ '^-?\d+$' then 'cc_employees:not_integer' end,
      case when cc_sq_ft is not null and cc_sq_ft !~ '^-?\d+$' then 'cc_sq_ft:not_integer' end,
      case when cc_mkt_id is not null and cc_mkt_id !~ '^-?\d+$' then 'cc_mkt_id:not_integer' end,
      case when cc_division is not null and cc_division !~ '^-?\d+$' then 'cc_division:not_integer' end,
      case when cc_company is not null and cc_company !~ '^-?\d+$' then 'cc_company:not_integer' end,
      case when cc_gmt_offset is not null and cc_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'cc_gmt_offset:not_numeric' end,
      case when cc_tax_percentage is not null and cc_tax_percentage !~ '^-?\d+(\.\d+)?$' then 'cc_tax_percentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    cc_call_center_sk,
    cc_call_center_id,
    cc_rec_start_date,
    cc_rec_end_date,
    cc_closed_date_sk,
    cc_open_date_sk,
    cc_name,
    cc_class,
    cc_employees,
    cc_sq_ft,
    cc_hours,
    cc_manager,
    cc_mkt_id,
    cc_mkt_class,
    cc_mkt_desc,
    cc_market_manager,
    cc_division,
    cc_division_name,
    cc_company,
    cc_company_name,
    cc_street_number,
    cc_street_name,
    cc_street_type,
    cc_suite_number,
    cc_city,
    cc_county,
    cc_state,
    cc_zip,
    cc_country,
    cc_gmt_offset,
    cc_tax_percentage,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
