-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_page') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when wp_web_page_sk is not null and wp_web_page_sk !~ '^-?\d+$' then 'wp_web_page_sk:not_integer' end,
      case when wp_rec_start_date is not null and wp_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'wp_rec_start_date:not_date' end,
      case when wp_rec_end_date is not null and wp_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'wp_rec_end_date:not_date' end,
      case when wp_creation_date_sk is not null and wp_creation_date_sk !~ '^-?\d+$' then 'wp_creation_date_sk:not_integer' end,
      case when wp_access_date_sk is not null and wp_access_date_sk !~ '^-?\d+$' then 'wp_access_date_sk:not_integer' end,
      case when wp_customer_sk is not null and wp_customer_sk !~ '^-?\d+$' then 'wp_customer_sk:not_integer' end,
      case when wp_char_count is not null and wp_char_count !~ '^-?\d+$' then 'wp_char_count:not_integer' end,
      case when wp_link_count is not null and wp_link_count !~ '^-?\d+$' then 'wp_link_count:not_integer' end,
      case when wp_image_count is not null and wp_image_count !~ '^-?\d+$' then 'wp_image_count:not_integer' end,
      case when wp_max_ad_count is not null and wp_max_ad_count !~ '^-?\d+$' then 'wp_max_ad_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    wp_web_page_sk,
    wp_web_page_id,
    wp_rec_start_date,
    wp_rec_end_date,
    wp_creation_date_sk,
    wp_access_date_sk,
    wp_autogen_flag,
    wp_customer_sk,
    wp_url,
    wp_type,
    wp_char_count,
    wp_link_count,
    wp_image_count,
    wp_max_ad_count,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
