-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'time_dim') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when t_time_sk is not null and t_time_sk !~ '^-?\d+$' then 't_time_sk:not_integer' end,
      case when t_time is not null and t_time !~ '^-?\d+$' then 't_time:not_integer' end,
      case when t_hour is not null and t_hour !~ '^-?\d+$' then 't_hour:not_integer' end,
      case when t_minute is not null and t_minute !~ '^-?\d+$' then 't_minute:not_integer' end,
      case when t_second is not null and t_second !~ '^-?\d+$' then 't_second:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when t_time_sk is null or t_time_sk ~ '^-?\d+$' then t_time_sk::integer end as t_time_sk,
    nullif(trim(t_time_id), '') as t_time_id,
    case when t_time is null or t_time ~ '^-?\d+$' then t_time::integer end as t_time,
    case when t_hour is null or t_hour ~ '^-?\d+$' then t_hour::integer end as t_hour,
    case when t_minute is null or t_minute ~ '^-?\d+$' then t_minute::integer end as t_minute,
    case when t_second is null or t_second ~ '^-?\d+$' then t_second::integer end as t_second,
    nullif(trim(t_am_pm), '') as t_am_pm,
    nullif(trim(t_shift), '') as t_shift,
    nullif(trim(t_sub_shift), '') as t_sub_shift,
    nullif(trim(t_meal_time), '') as t_meal_time
from validated
where array_length(_anomaly_reasons, 1) is null
