-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'promotion') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when p_promo_sk is not null and p_promo_sk !~ '^-?\d+$' then 'p_promo_sk:not_integer' end,
      case when p_start_date_sk is not null and p_start_date_sk !~ '^-?\d+$' then 'p_start_date_sk:not_integer' end,
      case when p_end_date_sk is not null and p_end_date_sk !~ '^-?\d+$' then 'p_end_date_sk:not_integer' end,
      case when p_item_sk is not null and p_item_sk !~ '^-?\d+$' then 'p_item_sk:not_integer' end,
      case when p_cost is not null and p_cost !~ '^-?\d+(\.\d+)?$' then 'p_cost:not_numeric' end,
      case when p_response_target is not null and p_response_target !~ '^-?\d+$' then 'p_response_target:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    p_promo_sk,
    p_promo_id,
    p_start_date_sk,
    p_end_date_sk,
    p_item_sk,
    p_cost,
    p_response_target,
    p_promo_name,
    p_channel_dmail,
    p_channel_email,
    p_channel_catalog,
    p_channel_tv,
    p_channel_radio,
    p_channel_press,
    p_channel_event,
    p_channel_demo,
    p_channel_details,
    p_purpose,
    p_discount_active,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
