-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when c_customer_sk is not null and c_customer_sk !~ '^-?\d+$' then 'c_customer_sk:not_integer' end,
      case when c_current_cdemo_sk is not null and c_current_cdemo_sk !~ '^-?\d+$' then 'c_current_cdemo_sk:not_integer' end,
      case when c_current_hdemo_sk is not null and c_current_hdemo_sk !~ '^-?\d+$' then 'c_current_hdemo_sk:not_integer' end,
      case when c_current_addr_sk is not null and c_current_addr_sk !~ '^-?\d+$' then 'c_current_addr_sk:not_integer' end,
      case when c_first_shipto_date_sk is not null and c_first_shipto_date_sk !~ '^-?\d+$' then 'c_first_shipto_date_sk:not_integer' end,
      case when c_first_sales_date_sk is not null and c_first_sales_date_sk !~ '^-?\d+$' then 'c_first_sales_date_sk:not_integer' end,
      case when c_birth_day is not null and c_birth_day !~ '^-?\d+$' then 'c_birth_day:not_integer' end,
      case when c_birth_month is not null and c_birth_month !~ '^-?\d+$' then 'c_birth_month:not_integer' end,
      case when c_birth_year is not null and c_birth_year !~ '^-?\d+$' then 'c_birth_year:not_integer' end,
      case when c_last_review_date_sk is not null and c_last_review_date_sk !~ '^-?\d+$' then 'c_last_review_date_sk:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    c_customer_sk,
    c_customer_id,
    c_current_cdemo_sk,
    c_current_hdemo_sk,
    c_current_addr_sk,
    c_first_shipto_date_sk,
    c_first_sales_date_sk,
    c_salutation,
    c_first_name,
    c_last_name,
    c_preferred_cust_flag,
    c_birth_day,
    c_birth_month,
    c_birth_year,
    c_birth_country,
    c_login,
    c_email_address,
    c_last_review_date_sk,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
