-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer_demographics') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cd_demo_sk is not null and cd_demo_sk !~ '^-?\d+$' then 'cd_demo_sk:not_integer' end,
      case when cd_purchase_estimate is not null and cd_purchase_estimate !~ '^-?\d+$' then 'cd_purchase_estimate:not_integer' end,
      case when cd_dep_count is not null and cd_dep_count !~ '^-?\d+$' then 'cd_dep_count:not_integer' end,
      case when cd_dep_employed_count is not null and cd_dep_employed_count !~ '^-?\d+$' then 'cd_dep_employed_count:not_integer' end,
      case when cd_dep_college_count is not null and cd_dep_college_count !~ '^-?\d+$' then 'cd_dep_college_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    cd_demo_sk,
    cd_gender,
    cd_marital_status,
    cd_education_status,
    cd_purchase_estimate,
    cd_credit_rating,
    cd_dep_count,
    cd_dep_employed_count,
    cd_dep_college_count,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
