-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'catalog_page') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cp_catalog_page_sk is not null and cp_catalog_page_sk !~ '^-?\d+$' then 'cp_catalog_page_sk:not_integer' end,
      case when cp_start_date_sk is not null and cp_start_date_sk !~ '^-?\d+$' then 'cp_start_date_sk:not_integer' end,
      case when cp_end_date_sk is not null and cp_end_date_sk !~ '^-?\d+$' then 'cp_end_date_sk:not_integer' end,
      case when cp_catalog_number is not null and cp_catalog_number !~ '^-?\d+$' then 'cp_catalog_number:not_integer' end,
      case when cp_catalog_page_number is not null and cp_catalog_page_number !~ '^-?\d+$' then 'cp_catalog_page_number:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    cp_catalog_page_sk,
    cp_catalog_page_id,
    cp_start_date_sk,
    cp_end_date_sk,
    cp_department,
    cp_catalog_number,
    cp_catalog_page_number,
    cp_description,
    cp_type,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
