-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'reason') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when r_reason_sk is not null and r_reason_sk !~ '^-?\d+$' then 'r_reason_sk:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when r_reason_sk is null or r_reason_sk ~ '^-?\d+$' then r_reason_sk::integer end as r_reason_sk,
    nullif(trim(r_reason_id), '') as r_reason_id,
    nullif(trim(r_reason_desc), '') as r_reason_desc
from validated
where array_length(_anomaly_reasons, 1) is null
