-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'household_demographics') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when hd_demo_sk is not null and hd_demo_sk !~ '^-?\d+$' then 'hd_demo_sk:not_integer' end,
      case when hd_income_band_sk is not null and hd_income_band_sk !~ '^-?\d+$' then 'hd_income_band_sk:not_integer' end,
      case when hd_dep_count is not null and hd_dep_count !~ '^-?\d+$' then 'hd_dep_count:not_integer' end,
      case when hd_vehicle_count is not null and hd_vehicle_count !~ '^-?\d+$' then 'hd_vehicle_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    hd_demo_sk,
    hd_income_band_sk,
    hd_buy_potential,
    hd_dep_count,
    hd_vehicle_count,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
