-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'time_dim') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when t_time_sk is not null and t_time_sk !~ '^-?\d+$' then 't_time_sk:not_integer' end,
      case when t_time is not null and t_time !~ '^-?\d+$' then 't_time:not_integer' end,
      case when t_hour is not null and t_hour !~ '^-?\d+$' then 't_hour:not_integer' end,
      case when t_minute is not null and t_minute !~ '^-?\d+$' then 't_minute:not_integer' end,
      case when t_second is not null and t_second !~ '^-?\d+$' then 't_second:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    t_time_sk,
    t_time_id,
    t_time,
    t_hour,
    t_minute,
    t_second,
    t_am_pm,
    t_shift,
    t_sub_shift,
    t_meal_time,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
