-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when c_customer_sk is not null and c_customer_sk !~ '^-?\d+$' then 'c_customer_sk:not_integer' end,
      case when c_current_cdemo_sk is not null and c_current_cdemo_sk !~ '^-?\d+$' then 'c_current_cdemo_sk:not_integer' end,
      case when c_current_hdemo_sk is not null and c_current_hdemo_sk !~ '^-?\d+$' then 'c_current_hdemo_sk:not_integer' end,
      case when c_current_addr_sk is not null and c_current_addr_sk !~ '^-?\d+$' then 'c_current_addr_sk:not_integer' end,
      case when c_first_shipto_date_sk is not null and c_first_shipto_date_sk !~ '^-?\d+$' then 'c_first_shipto_date_sk:not_integer' end,
      case when c_first_sales_date_sk is not null and c_first_sales_date_sk !~ '^-?\d+$' then 'c_first_sales_date_sk:not_integer' end,
      case when c_birth_day is not null and c_birth_day !~ '^-?\d+$' then 'c_birth_day:not_integer' end,
      case when c_birth_month is not null and c_birth_month !~ '^-?\d+$' then 'c_birth_month:not_integer' end,
      case when c_birth_year is not null and c_birth_year !~ '^-?\d+$' then 'c_birth_year:not_integer' end,
      case when c_last_review_date_sk is not null and c_last_review_date_sk !~ '^-?\d+$' then 'c_last_review_date_sk:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when c_customer_sk is null or c_customer_sk ~ '^-?\d+$' then c_customer_sk::integer end as c_customer_sk,
    nullif(trim(c_customer_id), '') as c_customer_id,
    case when c_current_cdemo_sk is null or c_current_cdemo_sk ~ '^-?\d+$' then c_current_cdemo_sk::integer end as c_current_cdemo_sk,
    case when c_current_hdemo_sk is null or c_current_hdemo_sk ~ '^-?\d+$' then c_current_hdemo_sk::integer end as c_current_hdemo_sk,
    case when c_current_addr_sk is null or c_current_addr_sk ~ '^-?\d+$' then c_current_addr_sk::integer end as c_current_addr_sk,
    case when c_first_shipto_date_sk is null or c_first_shipto_date_sk ~ '^-?\d+$' then c_first_shipto_date_sk::integer end as c_first_shipto_date_sk,
    case when c_first_sales_date_sk is null or c_first_sales_date_sk ~ '^-?\d+$' then c_first_sales_date_sk::integer end as c_first_sales_date_sk,
    nullif(trim(c_salutation), '') as c_salutation,
    nullif(trim(c_first_name), '') as c_first_name,
    nullif(trim(c_last_name), '') as c_last_name,
    nullif(trim(c_preferred_cust_flag), '') as c_preferred_cust_flag,
    case when c_birth_day is null or c_birth_day ~ '^-?\d+$' then c_birth_day::integer end as c_birth_day,
    case when c_birth_month is null or c_birth_month ~ '^-?\d+$' then c_birth_month::integer end as c_birth_month,
    case when c_birth_year is null or c_birth_year ~ '^-?\d+$' then c_birth_year::integer end as c_birth_year,
    nullif(trim(c_birth_country), '') as c_birth_country,
    nullif(trim(c_login), '') as c_login,
    nullif(trim(c_email_address), '') as c_email_address,
    case when c_last_review_date_sk is null or c_last_review_date_sk ~ '^-?\d+$' then c_last_review_date_sk::integer end as c_last_review_date_sk
from validated
where array_length(_anomaly_reasons, 1) is null
