-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'store') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when s_store_sk is not null and s_store_sk !~ '^-?\d+$' then 's_store_sk:not_integer' end,
      case when s_rec_start_date is not null and s_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 's_rec_start_date:not_date' end,
      case when s_rec_end_date is not null and s_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 's_rec_end_date:not_date' end,
      case when s_closed_date_sk is not null and s_closed_date_sk !~ '^-?\d+$' then 's_closed_date_sk:not_integer' end,
      case when s_number_employees is not null and s_number_employees !~ '^-?\d+$' then 's_number_employees:not_integer' end,
      case when s_floor_space is not null and s_floor_space !~ '^-?\d+$' then 's_floor_space:not_integer' end,
      case when s_market_id is not null and s_market_id !~ '^-?\d+$' then 's_market_id:not_integer' end,
      case when s_division_id is not null and s_division_id !~ '^-?\d+$' then 's_division_id:not_integer' end,
      case when s_company_id is not null and s_company_id !~ '^-?\d+$' then 's_company_id:not_integer' end,
      case when s_gmt_offset is not null and s_gmt_offset !~ '^-?\d+(\.\d+)?$' then 's_gmt_offset:not_numeric' end,
      case when s_tax_precentage is not null and s_tax_precentage !~ '^-?\d+(\.\d+)?$' then 's_tax_precentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when s_store_sk is null or s_store_sk ~ '^-?\d+$' then s_store_sk::integer end as s_store_sk,
    nullif(trim(s_store_id), '') as s_store_id,
    case when s_rec_start_date is null or s_rec_start_date ~ '^\d{4}-\d{2}-\d{2}$' then s_rec_start_date::date end as s_rec_start_date,
    case when s_rec_end_date is null or s_rec_end_date ~ '^\d{4}-\d{2}-\d{2}$' then s_rec_end_date::date end as s_rec_end_date,
    case when s_closed_date_sk is null or s_closed_date_sk ~ '^-?\d+$' then s_closed_date_sk::integer end as s_closed_date_sk,
    nullif(trim(s_store_name), '') as s_store_name,
    case when s_number_employees is null or s_number_employees ~ '^-?\d+$' then s_number_employees::integer end as s_number_employees,
    case when s_floor_space is null or s_floor_space ~ '^-?\d+$' then s_floor_space::integer end as s_floor_space,
    nullif(trim(s_hours), '') as s_hours,
    nullif(trim(s_manager), '') as s_manager,
    case when s_market_id is null or s_market_id ~ '^-?\d+$' then s_market_id::integer end as s_market_id,
    nullif(trim(s_geography_class), '') as s_geography_class,
    nullif(trim(s_market_desc), '') as s_market_desc,
    nullif(trim(s_market_manager), '') as s_market_manager,
    case when s_division_id is null or s_division_id ~ '^-?\d+$' then s_division_id::integer end as s_division_id,
    nullif(trim(s_division_name), '') as s_division_name,
    case when s_company_id is null or s_company_id ~ '^-?\d+$' then s_company_id::integer end as s_company_id,
    nullif(trim(s_company_name), '') as s_company_name,
    nullif(trim(s_street_number), '') as s_street_number,
    nullif(trim(s_street_name), '') as s_street_name,
    nullif(trim(s_street_type), '') as s_street_type,
    nullif(trim(s_suite_number), '') as s_suite_number,
    nullif(trim(s_city), '') as s_city,
    nullif(trim(s_county), '') as s_county,
    nullif(trim(s_state), '') as s_state,
    nullif(trim(s_zip), '') as s_zip,
    nullif(trim(s_country), '') as s_country,
    case when s_gmt_offset is null or s_gmt_offset ~ '^-?\d+(\.\d+)?$' then s_gmt_offset::numeric(7,2) end as s_gmt_offset,
    case when s_tax_precentage is null or s_tax_precentage ~ '^-?\d+(\.\d+)?$' then s_tax_precentage::numeric(7,2) end as s_tax_precentage
from validated
where array_length(_anomaly_reasons, 1) is null
