-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'catalog_page') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cp_catalog_page_sk is not null and cp_catalog_page_sk !~ '^-?\d+$' then 'cp_catalog_page_sk:not_integer' end,
      case when cp_start_date_sk is not null and cp_start_date_sk !~ '^-?\d+$' then 'cp_start_date_sk:not_integer' end,
      case when cp_end_date_sk is not null and cp_end_date_sk !~ '^-?\d+$' then 'cp_end_date_sk:not_integer' end,
      case when cp_catalog_number is not null and cp_catalog_number !~ '^-?\d+$' then 'cp_catalog_number:not_integer' end,
      case when cp_catalog_page_number is not null and cp_catalog_page_number !~ '^-?\d+$' then 'cp_catalog_page_number:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when cp_catalog_page_sk is null or cp_catalog_page_sk ~ '^-?\d+$' then cp_catalog_page_sk::integer end as cp_catalog_page_sk,
    nullif(trim(cp_catalog_page_id), '') as cp_catalog_page_id,
    case when cp_start_date_sk is null or cp_start_date_sk ~ '^-?\d+$' then cp_start_date_sk::integer end as cp_start_date_sk,
    case when cp_end_date_sk is null or cp_end_date_sk ~ '^-?\d+$' then cp_end_date_sk::integer end as cp_end_date_sk,
    nullif(trim(cp_department), '') as cp_department,
    case when cp_catalog_number is null or cp_catalog_number ~ '^-?\d+$' then cp_catalog_number::integer end as cp_catalog_number,
    case when cp_catalog_page_number is null or cp_catalog_page_number ~ '^-?\d+$' then cp_catalog_page_number::integer end as cp_catalog_page_number,
    nullif(trim(cp_description), '') as cp_description,
    nullif(trim(cp_type), '') as cp_type
from validated
where array_length(_anomaly_reasons, 1) is null
