-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'ship_mode') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when sm_ship_mode_sk is not null and sm_ship_mode_sk !~ '^-?\d+$' then 'sm_ship_mode_sk:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when sm_ship_mode_sk is null or sm_ship_mode_sk ~ '^-?\d+$' then sm_ship_mode_sk::integer end as sm_ship_mode_sk,
    nullif(trim(sm_ship_mode_id), '') as sm_ship_mode_id,
    nullif(trim(sm_type), '') as sm_type,
    nullif(trim(sm_code), '') as sm_code,
    nullif(trim(sm_carrier), '') as sm_carrier,
    nullif(trim(sm_contract), '') as sm_contract
from validated
where array_length(_anomaly_reasons, 1) is null
