-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer_address') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when ca_address_sk is not null and ca_address_sk !~ '^-?\d+$' then 'ca_address_sk:not_integer' end,
      case when ca_gmt_offset is not null and ca_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'ca_gmt_offset:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when ca_address_sk is null or ca_address_sk ~ '^-?\d+$' then ca_address_sk::integer end as ca_address_sk,
    nullif(trim(ca_address_id), '') as ca_address_id,
    nullif(trim(ca_street_number), '') as ca_street_number,
    nullif(trim(ca_street_name), '') as ca_street_name,
    nullif(trim(ca_street_type), '') as ca_street_type,
    nullif(trim(ca_suite_number), '') as ca_suite_number,
    nullif(trim(ca_city), '') as ca_city,
    nullif(trim(ca_county), '') as ca_county,
    nullif(trim(ca_state), '') as ca_state,
    nullif(trim(ca_zip), '') as ca_zip,
    nullif(trim(ca_country), '') as ca_country,
    case when ca_gmt_offset is null or ca_gmt_offset ~ '^-?\d+(\.\d+)?$' then ca_gmt_offset::numeric(7,2) end as ca_gmt_offset,
    nullif(trim(ca_location_type), '') as ca_location_type
from validated
where array_length(_anomaly_reasons, 1) is null
