-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_page') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when wp_web_page_sk is not null and wp_web_page_sk !~ '^-?\d+$' then 'wp_web_page_sk:not_integer' end,
      case when wp_rec_start_date is not null and wp_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'wp_rec_start_date:not_date' end,
      case when wp_rec_end_date is not null and wp_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'wp_rec_end_date:not_date' end,
      case when wp_creation_date_sk is not null and wp_creation_date_sk !~ '^-?\d+$' then 'wp_creation_date_sk:not_integer' end,
      case when wp_access_date_sk is not null and wp_access_date_sk !~ '^-?\d+$' then 'wp_access_date_sk:not_integer' end,
      case when wp_customer_sk is not null and wp_customer_sk !~ '^-?\d+$' then 'wp_customer_sk:not_integer' end,
      case when wp_char_count is not null and wp_char_count !~ '^-?\d+$' then 'wp_char_count:not_integer' end,
      case when wp_link_count is not null and wp_link_count !~ '^-?\d+$' then 'wp_link_count:not_integer' end,
      case when wp_image_count is not null and wp_image_count !~ '^-?\d+$' then 'wp_image_count:not_integer' end,
      case when wp_max_ad_count is not null and wp_max_ad_count !~ '^-?\d+$' then 'wp_max_ad_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when wp_web_page_sk is null or wp_web_page_sk ~ '^-?\d+$' then wp_web_page_sk::integer end as wp_web_page_sk,
    nullif(trim(wp_web_page_id), '') as wp_web_page_id,
    case when wp_rec_start_date is null or wp_rec_start_date ~ '^\d{4}-\d{2}-\d{2}$' then wp_rec_start_date::date end as wp_rec_start_date,
    case when wp_rec_end_date is null or wp_rec_end_date ~ '^\d{4}-\d{2}-\d{2}$' then wp_rec_end_date::date end as wp_rec_end_date,
    case when wp_creation_date_sk is null or wp_creation_date_sk ~ '^-?\d+$' then wp_creation_date_sk::integer end as wp_creation_date_sk,
    case when wp_access_date_sk is null or wp_access_date_sk ~ '^-?\d+$' then wp_access_date_sk::integer end as wp_access_date_sk,
    nullif(trim(wp_autogen_flag), '') as wp_autogen_flag,
    case when wp_customer_sk is null or wp_customer_sk ~ '^-?\d+$' then wp_customer_sk::integer end as wp_customer_sk,
    nullif(trim(wp_url), '') as wp_url,
    nullif(trim(wp_type), '') as wp_type,
    case when wp_char_count is null or wp_char_count ~ '^-?\d+$' then wp_char_count::integer end as wp_char_count,
    case when wp_link_count is null or wp_link_count ~ '^-?\d+$' then wp_link_count::integer end as wp_link_count,
    case when wp_image_count is null or wp_image_count ~ '^-?\d+$' then wp_image_count::integer end as wp_image_count,
    case when wp_max_ad_count is null or wp_max_ad_count ~ '^-?\d+$' then wp_max_ad_count::integer end as wp_max_ad_count
from validated
where array_length(_anomaly_reasons, 1) is null
