-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'date_dim') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when d_date_sk is not null and d_date_sk !~ '^-?\d+$' then 'd_date_sk:not_integer' end,
      case when d_date is not null and d_date !~ '^\d{4}-\d{2}-\d{2}$' then 'd_date:not_date' end,
      case when d_month_seq is not null and d_month_seq !~ '^-?\d+$' then 'd_month_seq:not_integer' end,
      case when d_week_seq is not null and d_week_seq !~ '^-?\d+$' then 'd_week_seq:not_integer' end,
      case when d_quarter_seq is not null and d_quarter_seq !~ '^-?\d+$' then 'd_quarter_seq:not_integer' end,
      case when d_year is not null and d_year !~ '^-?\d+$' then 'd_year:not_integer' end,
      case when d_dow is not null and d_dow !~ '^-?\d+$' then 'd_dow:not_integer' end,
      case when d_moy is not null and d_moy !~ '^-?\d+$' then 'd_moy:not_integer' end,
      case when d_dom is not null and d_dom !~ '^-?\d+$' then 'd_dom:not_integer' end,
      case when d_qoy is not null and d_qoy !~ '^-?\d+$' then 'd_qoy:not_integer' end,
      case when d_fy_year is not null and d_fy_year !~ '^-?\d+$' then 'd_fy_year:not_integer' end,
      case when d_fy_quarter_seq is not null and d_fy_quarter_seq !~ '^-?\d+$' then 'd_fy_quarter_seq:not_integer' end,
      case when d_fy_week_seq is not null and d_fy_week_seq !~ '^-?\d+$' then 'd_fy_week_seq:not_integer' end,
      case when d_first_dom is not null and d_first_dom !~ '^-?\d+$' then 'd_first_dom:not_integer' end,
      case when d_last_dom is not null and d_last_dom !~ '^-?\d+$' then 'd_last_dom:not_integer' end,
      case when d_same_day_ly is not null and d_same_day_ly !~ '^-?\d+$' then 'd_same_day_ly:not_integer' end,
      case when d_same_day_lq is not null and d_same_day_lq !~ '^-?\d+$' then 'd_same_day_lq:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    d_date_sk,
    d_date_id,
    d_date,
    d_month_seq,
    d_week_seq,
    d_quarter_seq,
    d_year,
    d_dow,
    d_moy,
    d_dom,
    d_qoy,
    d_fy_year,
    d_fy_quarter_seq,
    d_fy_week_seq,
    d_day_name,
    d_quarter_name,
    d_holiday,
    d_weekend,
    d_following_holiday,
    d_first_dom,
    d_last_dom,
    d_same_day_ly,
    d_same_day_lq,
    d_current_day,
    d_current_week,
    d_current_month,
    d_current_quarter,
    d_current_year,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
