-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'ship_mode') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when sm_ship_mode_sk is not null and sm_ship_mode_sk !~ '^-?\d+$' then 'sm_ship_mode_sk:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    sm_ship_mode_sk,
    sm_ship_mode_id,
    sm_type,
    sm_code,
    sm_carrier,
    sm_contract,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
