-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'item') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when i_item_sk is not null and i_item_sk !~ '^-?\d+$' then 'i_item_sk:not_integer' end,
      case when i_rec_start_date is not null and i_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'i_rec_start_date:not_date' end,
      case when i_rec_end_date is not null and i_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'i_rec_end_date:not_date' end,
      case when i_current_price is not null and i_current_price !~ '^-?\d+(\.\d+)?$' then 'i_current_price:not_numeric' end,
      case when i_wholesale_cost is not null and i_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'i_wholesale_cost:not_numeric' end,
      case when i_brand_id is not null and i_brand_id !~ '^-?\d+$' then 'i_brand_id:not_integer' end,
      case when i_class_id is not null and i_class_id !~ '^-?\d+$' then 'i_class_id:not_integer' end,
      case when i_category_id is not null and i_category_id !~ '^-?\d+$' then 'i_category_id:not_integer' end,
      case when i_manufact_id is not null and i_manufact_id !~ '^-?\d+$' then 'i_manufact_id:not_integer' end,
      case when i_manager_id is not null and i_manager_id !~ '^-?\d+$' then 'i_manager_id:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    i_item_sk,
    i_item_id,
    i_rec_start_date,
    i_rec_end_date,
    i_item_desc,
    i_current_price,
    i_wholesale_cost,
    i_brand_id,
    i_brand,
    i_class_id,
    i_class,
    i_category_id,
    i_category,
    i_manufact_id,
    i_manufact,
    i_size,
    i_formulation,
    i_color,
    i_units,
    i_container,
    i_manager_id,
    i_product_name,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
