-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'item') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when i_item_sk is not null and i_item_sk !~ '^-?\d+$' then 'i_item_sk:not_integer' end,
      case when i_rec_start_date is not null and i_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'i_rec_start_date:not_date' end,
      case when i_rec_end_date is not null and i_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'i_rec_end_date:not_date' end,
      case when i_current_price is not null and i_current_price !~ '^-?\d+(\.\d+)?$' then 'i_current_price:not_numeric' end,
      case when i_wholesale_cost is not null and i_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'i_wholesale_cost:not_numeric' end,
      case when i_brand_id is not null and i_brand_id !~ '^-?\d+$' then 'i_brand_id:not_integer' end,
      case when i_class_id is not null and i_class_id !~ '^-?\d+$' then 'i_class_id:not_integer' end,
      case when i_category_id is not null and i_category_id !~ '^-?\d+$' then 'i_category_id:not_integer' end,
      case when i_manufact_id is not null and i_manufact_id !~ '^-?\d+$' then 'i_manufact_id:not_integer' end,
      case when i_manager_id is not null and i_manager_id !~ '^-?\d+$' then 'i_manager_id:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when i_item_sk is null or i_item_sk ~ '^-?\d+$' then i_item_sk::integer end as i_item_sk,
    nullif(trim(i_item_id), '') as i_item_id,
    case when i_rec_start_date is null or i_rec_start_date ~ '^\d{4}-\d{2}-\d{2}$' then i_rec_start_date::date end as i_rec_start_date,
    case when i_rec_end_date is null or i_rec_end_date ~ '^\d{4}-\d{2}-\d{2}$' then i_rec_end_date::date end as i_rec_end_date,
    nullif(trim(i_item_desc), '') as i_item_desc,
    case when i_current_price is null or i_current_price ~ '^-?\d+(\.\d+)?$' then i_current_price::numeric(7,2) end as i_current_price,
    case when i_wholesale_cost is null or i_wholesale_cost ~ '^-?\d+(\.\d+)?$' then i_wholesale_cost::numeric(7,2) end as i_wholesale_cost,
    case when i_brand_id is null or i_brand_id ~ '^-?\d+$' then i_brand_id::integer end as i_brand_id,
    nullif(trim(i_brand), '') as i_brand,
    case when i_class_id is null or i_class_id ~ '^-?\d+$' then i_class_id::integer end as i_class_id,
    nullif(trim(i_class), '') as i_class,
    case when i_category_id is null or i_category_id ~ '^-?\d+$' then i_category_id::integer end as i_category_id,
    nullif(trim(i_category), '') as i_category,
    case when i_manufact_id is null or i_manufact_id ~ '^-?\d+$' then i_manufact_id::integer end as i_manufact_id,
    nullif(trim(i_manufact), '') as i_manufact,
    nullif(trim(i_size), '') as i_size,
    nullif(trim(i_formulation), '') as i_formulation,
    nullif(trim(i_color), '') as i_color,
    nullif(trim(i_units), '') as i_units,
    nullif(trim(i_container), '') as i_container,
    case when i_manager_id is null or i_manager_id ~ '^-?\d+$' then i_manager_id::integer end as i_manager_id,
    nullif(trim(i_product_name), '') as i_product_name
from validated
where array_length(_anomaly_reasons, 1) is null
