-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'household_demographics') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when hd_demo_sk is not null and hd_demo_sk !~ '^-?\d+$' then 'hd_demo_sk:not_integer' end,
      case when hd_income_band_sk is not null and hd_income_band_sk !~ '^-?\d+$' then 'hd_income_band_sk:not_integer' end,
      case when hd_dep_count is not null and hd_dep_count !~ '^-?\d+$' then 'hd_dep_count:not_integer' end,
      case when hd_vehicle_count is not null and hd_vehicle_count !~ '^-?\d+$' then 'hd_vehicle_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when hd_demo_sk is null or hd_demo_sk ~ '^-?\d+$' then hd_demo_sk::integer end as hd_demo_sk,
    case when hd_income_band_sk is null or hd_income_band_sk ~ '^-?\d+$' then hd_income_band_sk::integer end as hd_income_band_sk,
    nullif(trim(hd_buy_potential), '') as hd_buy_potential,
    case when hd_dep_count is null or hd_dep_count ~ '^-?\d+$' then hd_dep_count::integer end as hd_dep_count,
    case when hd_vehicle_count is null or hd_vehicle_count ~ '^-?\d+$' then hd_vehicle_count::integer end as hd_vehicle_count
from validated
where array_length(_anomaly_reasons, 1) is null
