-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer_demographics') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cd_demo_sk is not null and cd_demo_sk !~ '^-?\d+$' then 'cd_demo_sk:not_integer' end,
      case when cd_purchase_estimate is not null and cd_purchase_estimate !~ '^-?\d+$' then 'cd_purchase_estimate:not_integer' end,
      case when cd_dep_count is not null and cd_dep_count !~ '^-?\d+$' then 'cd_dep_count:not_integer' end,
      case when cd_dep_employed_count is not null and cd_dep_employed_count !~ '^-?\d+$' then 'cd_dep_employed_count:not_integer' end,
      case when cd_dep_college_count is not null and cd_dep_college_count !~ '^-?\d+$' then 'cd_dep_college_count:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when cd_demo_sk is null or cd_demo_sk ~ '^-?\d+$' then cd_demo_sk::integer end as cd_demo_sk,
    nullif(trim(cd_gender), '') as cd_gender,
    nullif(trim(cd_marital_status), '') as cd_marital_status,
    nullif(trim(cd_education_status), '') as cd_education_status,
    case when cd_purchase_estimate is null or cd_purchase_estimate ~ '^-?\d+$' then cd_purchase_estimate::integer end as cd_purchase_estimate,
    nullif(trim(cd_credit_rating), '') as cd_credit_rating,
    case when cd_dep_count is null or cd_dep_count ~ '^-?\d+$' then cd_dep_count::integer end as cd_dep_count,
    case when cd_dep_employed_count is null or cd_dep_employed_count ~ '^-?\d+$' then cd_dep_employed_count::integer end as cd_dep_employed_count,
    case when cd_dep_college_count is null or cd_dep_college_count ~ '^-?\d+$' then cd_dep_college_count::integer end as cd_dep_college_count
from validated
where array_length(_anomaly_reasons, 1) is null
