-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'promotion') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when p_promo_sk is not null and p_promo_sk !~ '^-?\d+$' then 'p_promo_sk:not_integer' end,
      case when p_start_date_sk is not null and p_start_date_sk !~ '^-?\d+$' then 'p_start_date_sk:not_integer' end,
      case when p_end_date_sk is not null and p_end_date_sk !~ '^-?\d+$' then 'p_end_date_sk:not_integer' end,
      case when p_item_sk is not null and p_item_sk !~ '^-?\d+$' then 'p_item_sk:not_integer' end,
      case when p_cost is not null and p_cost !~ '^-?\d+(\.\d+)?$' then 'p_cost:not_numeric' end,
      case when p_response_target is not null and p_response_target !~ '^-?\d+$' then 'p_response_target:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when p_promo_sk is null or p_promo_sk ~ '^-?\d+$' then p_promo_sk::integer end as p_promo_sk,
    nullif(trim(p_promo_id), '') as p_promo_id,
    case when p_start_date_sk is null or p_start_date_sk ~ '^-?\d+$' then p_start_date_sk::integer end as p_start_date_sk,
    case when p_end_date_sk is null or p_end_date_sk ~ '^-?\d+$' then p_end_date_sk::integer end as p_end_date_sk,
    case when p_item_sk is null or p_item_sk ~ '^-?\d+$' then p_item_sk::integer end as p_item_sk,
    case when p_cost is null or p_cost ~ '^-?\d+(\.\d+)?$' then p_cost::numeric(7,2) end as p_cost,
    case when p_response_target is null or p_response_target ~ '^-?\d+$' then p_response_target::integer end as p_response_target,
    nullif(trim(p_promo_name), '') as p_promo_name,
    nullif(trim(p_channel_dmail), '') as p_channel_dmail,
    nullif(trim(p_channel_email), '') as p_channel_email,
    nullif(trim(p_channel_catalog), '') as p_channel_catalog,
    nullif(trim(p_channel_tv), '') as p_channel_tv,
    nullif(trim(p_channel_radio), '') as p_channel_radio,
    nullif(trim(p_channel_press), '') as p_channel_press,
    nullif(trim(p_channel_event), '') as p_channel_event,
    nullif(trim(p_channel_demo), '') as p_channel_demo,
    nullif(trim(p_channel_details), '') as p_channel_details,
    nullif(trim(p_purpose), '') as p_purpose,
    nullif(trim(p_discount_active), '') as p_discount_active
from validated
where array_length(_anomaly_reasons, 1) is null
