-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_site') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when web_site_sk is not null and web_site_sk !~ '^-?\d+$' then 'web_site_sk:not_integer' end,
      case when web_rec_start_date is not null and web_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'web_rec_start_date:not_date' end,
      case when web_rec_end_date is not null and web_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'web_rec_end_date:not_date' end,
      case when web_open_date_sk is not null and web_open_date_sk !~ '^-?\d+$' then 'web_open_date_sk:not_integer' end,
      case when web_close_date_sk is not null and web_close_date_sk !~ '^-?\d+$' then 'web_close_date_sk:not_integer' end,
      case when web_mkt_id is not null and web_mkt_id !~ '^-?\d+$' then 'web_mkt_id:not_integer' end,
      case when web_company_id is not null and web_company_id !~ '^-?\d+$' then 'web_company_id:not_integer' end,
      case when web_gmt_offset is not null and web_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'web_gmt_offset:not_numeric' end,
      case when web_tax_percentage is not null and web_tax_percentage !~ '^-?\d+(\.\d+)?$' then 'web_tax_percentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    web_site_sk,
    web_site_id,
    web_rec_start_date,
    web_rec_end_date,
    web_name,
    web_open_date_sk,
    web_close_date_sk,
    web_class,
    web_manager,
    web_mkt_id,
    web_mkt_class,
    web_mkt_desc,
    web_market_manager,
    web_company_id,
    web_company_name,
    web_street_number,
    web_street_name,
    web_street_type,
    web_suite_number,
    web_city,
    web_county,
    web_state,
    web_zip,
    web_country,
    web_gmt_offset,
    web_tax_percentage,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
