-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'warehouse') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when w_warehouse_sk is not null and w_warehouse_sk !~ '^-?\d+$' then 'w_warehouse_sk:not_integer' end,
      case when w_warehouse_sq_ft is not null and w_warehouse_sq_ft !~ '^-?\d+$' then 'w_warehouse_sq_ft:not_integer' end,
      case when w_gmt_offset is not null and w_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'w_gmt_offset:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    w_warehouse_sk,
    w_warehouse_id,
    w_warehouse_name,
    w_warehouse_sq_ft,
    w_street_number,
    w_street_name,
    w_street_type,
    w_suite_number,
    w_city,
    w_county,
    w_state,
    w_zip,
    w_country,
    w_gmt_offset,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
