-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'warehouse') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when w_warehouse_sk is not null and w_warehouse_sk !~ '^-?\d+$' then 'w_warehouse_sk:not_integer' end,
      case when w_warehouse_sq_ft is not null and w_warehouse_sq_ft !~ '^-?\d+$' then 'w_warehouse_sq_ft:not_integer' end,
      case when w_gmt_offset is not null and w_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'w_gmt_offset:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when w_warehouse_sk is null or w_warehouse_sk ~ '^-?\d+$' then w_warehouse_sk::integer end as w_warehouse_sk,
    nullif(trim(w_warehouse_id), '') as w_warehouse_id,
    nullif(trim(w_warehouse_name), '') as w_warehouse_name,
    case when w_warehouse_sq_ft is null or w_warehouse_sq_ft ~ '^-?\d+$' then w_warehouse_sq_ft::integer end as w_warehouse_sq_ft,
    nullif(trim(w_street_number), '') as w_street_number,
    nullif(trim(w_street_name), '') as w_street_name,
    nullif(trim(w_street_type), '') as w_street_type,
    nullif(trim(w_suite_number), '') as w_suite_number,
    nullif(trim(w_city), '') as w_city,
    nullif(trim(w_county), '') as w_county,
    nullif(trim(w_state), '') as w_state,
    nullif(trim(w_zip), '') as w_zip,
    nullif(trim(w_country), '') as w_country,
    case when w_gmt_offset is null or w_gmt_offset ~ '^-?\d+(\.\d+)?$' then w_gmt_offset::numeric(7,2) end as w_gmt_offset
from validated
where array_length(_anomaly_reasons, 1) is null
