-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'income_band') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when ib_income_band_sk is not null and ib_income_band_sk !~ '^-?\d+$' then 'ib_income_band_sk:not_integer' end,
      case when ib_lower_bound is not null and ib_lower_bound !~ '^-?\d+$' then 'ib_lower_bound:not_integer' end,
      case when ib_upper_bound is not null and ib_upper_bound !~ '^-?\d+$' then 'ib_upper_bound:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when ib_income_band_sk is null or ib_income_band_sk ~ '^-?\d+$' then ib_income_band_sk::integer end as ib_income_band_sk,
    case when ib_lower_bound is null or ib_lower_bound ~ '^-?\d+$' then ib_lower_bound::integer end as ib_lower_bound,
    case when ib_upper_bound is null or ib_upper_bound ~ '^-?\d+$' then ib_upper_bound::integer end as ib_upper_bound
from validated
where array_length(_anomaly_reasons, 1) is null
