-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'date_dim') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when d_date_sk is not null and d_date_sk !~ '^-?\d+$' then 'd_date_sk:not_integer' end,
      case when d_date is not null and d_date !~ '^\d{4}-\d{2}-\d{2}$' then 'd_date:not_date' end,
      case when d_month_seq is not null and d_month_seq !~ '^-?\d+$' then 'd_month_seq:not_integer' end,
      case when d_week_seq is not null and d_week_seq !~ '^-?\d+$' then 'd_week_seq:not_integer' end,
      case when d_quarter_seq is not null and d_quarter_seq !~ '^-?\d+$' then 'd_quarter_seq:not_integer' end,
      case when d_year is not null and d_year !~ '^-?\d+$' then 'd_year:not_integer' end,
      case when d_dow is not null and d_dow !~ '^-?\d+$' then 'd_dow:not_integer' end,
      case when d_moy is not null and d_moy !~ '^-?\d+$' then 'd_moy:not_integer' end,
      case when d_dom is not null and d_dom !~ '^-?\d+$' then 'd_dom:not_integer' end,
      case when d_qoy is not null and d_qoy !~ '^-?\d+$' then 'd_qoy:not_integer' end,
      case when d_fy_year is not null and d_fy_year !~ '^-?\d+$' then 'd_fy_year:not_integer' end,
      case when d_fy_quarter_seq is not null and d_fy_quarter_seq !~ '^-?\d+$' then 'd_fy_quarter_seq:not_integer' end,
      case when d_fy_week_seq is not null and d_fy_week_seq !~ '^-?\d+$' then 'd_fy_week_seq:not_integer' end,
      case when d_first_dom is not null and d_first_dom !~ '^-?\d+$' then 'd_first_dom:not_integer' end,
      case when d_last_dom is not null and d_last_dom !~ '^-?\d+$' then 'd_last_dom:not_integer' end,
      case when d_same_day_ly is not null and d_same_day_ly !~ '^-?\d+$' then 'd_same_day_ly:not_integer' end,
      case when d_same_day_lq is not null and d_same_day_lq !~ '^-?\d+$' then 'd_same_day_lq:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when d_date_sk is null or d_date_sk ~ '^-?\d+$' then d_date_sk::integer end as d_date_sk,
    nullif(trim(d_date_id), '') as d_date_id,
    case when d_date is null or d_date ~ '^\d{4}-\d{2}-\d{2}$' then d_date::date end as d_date,
    case when d_month_seq is null or d_month_seq ~ '^-?\d+$' then d_month_seq::integer end as d_month_seq,
    case when d_week_seq is null or d_week_seq ~ '^-?\d+$' then d_week_seq::integer end as d_week_seq,
    case when d_quarter_seq is null or d_quarter_seq ~ '^-?\d+$' then d_quarter_seq::integer end as d_quarter_seq,
    case when d_year is null or d_year ~ '^-?\d+$' then d_year::integer end as d_year,
    case when d_dow is null or d_dow ~ '^-?\d+$' then d_dow::integer end as d_dow,
    case when d_moy is null or d_moy ~ '^-?\d+$' then d_moy::integer end as d_moy,
    case when d_dom is null or d_dom ~ '^-?\d+$' then d_dom::integer end as d_dom,
    case when d_qoy is null or d_qoy ~ '^-?\d+$' then d_qoy::integer end as d_qoy,
    case when d_fy_year is null or d_fy_year ~ '^-?\d+$' then d_fy_year::integer end as d_fy_year,
    case when d_fy_quarter_seq is null or d_fy_quarter_seq ~ '^-?\d+$' then d_fy_quarter_seq::integer end as d_fy_quarter_seq,
    case when d_fy_week_seq is null or d_fy_week_seq ~ '^-?\d+$' then d_fy_week_seq::integer end as d_fy_week_seq,
    nullif(trim(d_day_name), '') as d_day_name,
    nullif(trim(d_quarter_name), '') as d_quarter_name,
    nullif(trim(d_holiday), '') as d_holiday,
    nullif(trim(d_weekend), '') as d_weekend,
    nullif(trim(d_following_holiday), '') as d_following_holiday,
    case when d_first_dom is null or d_first_dom ~ '^-?\d+$' then d_first_dom::integer end as d_first_dom,
    case when d_last_dom is null or d_last_dom ~ '^-?\d+$' then d_last_dom::integer end as d_last_dom,
    case when d_same_day_ly is null or d_same_day_ly ~ '^-?\d+$' then d_same_day_ly::integer end as d_same_day_ly,
    case when d_same_day_lq is null or d_same_day_lq ~ '^-?\d+$' then d_same_day_lq::integer end as d_same_day_lq,
    nullif(trim(d_current_day), '') as d_current_day,
    nullif(trim(d_current_week), '') as d_current_week,
    nullif(trim(d_current_month), '') as d_current_month,
    nullif(trim(d_current_quarter), '') as d_current_quarter,
    nullif(trim(d_current_year), '') as d_current_year
from validated
where array_length(_anomaly_reasons, 1) is null
