-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'customer_address') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when ca_address_sk is not null and ca_address_sk !~ '^-?\d+$' then 'ca_address_sk:not_integer' end,
      case when ca_gmt_offset is not null and ca_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'ca_gmt_offset:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    ca_address_sk,
    ca_address_id,
    ca_street_number,
    ca_street_name,
    ca_street_type,
    ca_suite_number,
    ca_city,
    ca_county,
    ca_state,
    ca_zip,
    ca_country,
    ca_gmt_offset,
    ca_location_type,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
