-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_site') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when web_site_sk is not null and web_site_sk !~ '^-?\d+$' then 'web_site_sk:not_integer' end,
      case when web_rec_start_date is not null and web_rec_start_date !~ '^\d{4}-\d{2}-\d{2}$' then 'web_rec_start_date:not_date' end,
      case when web_rec_end_date is not null and web_rec_end_date !~ '^\d{4}-\d{2}-\d{2}$' then 'web_rec_end_date:not_date' end,
      case when web_open_date_sk is not null and web_open_date_sk !~ '^-?\d+$' then 'web_open_date_sk:not_integer' end,
      case when web_close_date_sk is not null and web_close_date_sk !~ '^-?\d+$' then 'web_close_date_sk:not_integer' end,
      case when web_mkt_id is not null and web_mkt_id !~ '^-?\d+$' then 'web_mkt_id:not_integer' end,
      case when web_company_id is not null and web_company_id !~ '^-?\d+$' then 'web_company_id:not_integer' end,
      case when web_gmt_offset is not null and web_gmt_offset !~ '^-?\d+(\.\d+)?$' then 'web_gmt_offset:not_numeric' end,
      case when web_tax_percentage is not null and web_tax_percentage !~ '^-?\d+(\.\d+)?$' then 'web_tax_percentage:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when web_site_sk is null or web_site_sk ~ '^-?\d+$' then web_site_sk::integer end as web_site_sk,
    nullif(trim(web_site_id), '') as web_site_id,
    case when web_rec_start_date is null or web_rec_start_date ~ '^\d{4}-\d{2}-\d{2}$' then web_rec_start_date::date end as web_rec_start_date,
    case when web_rec_end_date is null or web_rec_end_date ~ '^\d{4}-\d{2}-\d{2}$' then web_rec_end_date::date end as web_rec_end_date,
    nullif(trim(web_name), '') as web_name,
    case when web_open_date_sk is null or web_open_date_sk ~ '^-?\d+$' then web_open_date_sk::integer end as web_open_date_sk,
    case when web_close_date_sk is null or web_close_date_sk ~ '^-?\d+$' then web_close_date_sk::integer end as web_close_date_sk,
    nullif(trim(web_class), '') as web_class,
    nullif(trim(web_manager), '') as web_manager,
    case when web_mkt_id is null or web_mkt_id ~ '^-?\d+$' then web_mkt_id::integer end as web_mkt_id,
    nullif(trim(web_mkt_class), '') as web_mkt_class,
    nullif(trim(web_mkt_desc), '') as web_mkt_desc,
    nullif(trim(web_market_manager), '') as web_market_manager,
    case when web_company_id is null or web_company_id ~ '^-?\d+$' then web_company_id::integer end as web_company_id,
    nullif(trim(web_company_name), '') as web_company_name,
    nullif(trim(web_street_number), '') as web_street_number,
    nullif(trim(web_street_name), '') as web_street_name,
    nullif(trim(web_street_type), '') as web_street_type,
    nullif(trim(web_suite_number), '') as web_suite_number,
    nullif(trim(web_city), '') as web_city,
    nullif(trim(web_county), '') as web_county,
    nullif(trim(web_state), '') as web_state,
    nullif(trim(web_zip), '') as web_zip,
    nullif(trim(web_country), '') as web_country,
    case when web_gmt_offset is null or web_gmt_offset ~ '^-?\d+(\.\d+)?$' then web_gmt_offset::numeric(7,2) end as web_gmt_offset,
    case when web_tax_percentage is null or web_tax_percentage ~ '^-?\d+(\.\d+)?$' then web_tax_percentage::numeric(7,2) end as web_tax_percentage
from validated
where array_length(_anomaly_reasons, 1) is null
