-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'catalog_sales') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cs_sold_date_sk is not null and cs_sold_date_sk !~ '^-?\d+$' then 'cs_sold_date_sk:not_integer' end,
      case when cs_sold_time_sk is not null and cs_sold_time_sk !~ '^-?\d+$' then 'cs_sold_time_sk:not_integer' end,
      case when cs_ship_date_sk is not null and cs_ship_date_sk !~ '^-?\d+$' then 'cs_ship_date_sk:not_integer' end,
      case when cs_bill_customer_sk is not null and cs_bill_customer_sk !~ '^-?\d+$' then 'cs_bill_customer_sk:not_integer' end,
      case when cs_bill_cdemo_sk is not null and cs_bill_cdemo_sk !~ '^-?\d+$' then 'cs_bill_cdemo_sk:not_integer' end,
      case when cs_bill_hdemo_sk is not null and cs_bill_hdemo_sk !~ '^-?\d+$' then 'cs_bill_hdemo_sk:not_integer' end,
      case when cs_bill_addr_sk is not null and cs_bill_addr_sk !~ '^-?\d+$' then 'cs_bill_addr_sk:not_integer' end,
      case when cs_ship_customer_sk is not null and cs_ship_customer_sk !~ '^-?\d+$' then 'cs_ship_customer_sk:not_integer' end,
      case when cs_ship_cdemo_sk is not null and cs_ship_cdemo_sk !~ '^-?\d+$' then 'cs_ship_cdemo_sk:not_integer' end,
      case when cs_ship_hdemo_sk is not null and cs_ship_hdemo_sk !~ '^-?\d+$' then 'cs_ship_hdemo_sk:not_integer' end,
      case when cs_ship_addr_sk is not null and cs_ship_addr_sk !~ '^-?\d+$' then 'cs_ship_addr_sk:not_integer' end,
      case when cs_call_center_sk is not null and cs_call_center_sk !~ '^-?\d+$' then 'cs_call_center_sk:not_integer' end,
      case when cs_catalog_page_sk is not null and cs_catalog_page_sk !~ '^-?\d+$' then 'cs_catalog_page_sk:not_integer' end,
      case when cs_ship_mode_sk is not null and cs_ship_mode_sk !~ '^-?\d+$' then 'cs_ship_mode_sk:not_integer' end,
      case when cs_warehouse_sk is not null and cs_warehouse_sk !~ '^-?\d+$' then 'cs_warehouse_sk:not_integer' end,
      case when cs_item_sk is not null and cs_item_sk !~ '^-?\d+$' then 'cs_item_sk:not_integer' end,
      case when cs_promo_sk is not null and cs_promo_sk !~ '^-?\d+$' then 'cs_promo_sk:not_integer' end,
      case when cs_order_number is not null and cs_order_number !~ '^-?\d+$' then 'cs_order_number:not_integer' end,
      case when cs_quantity is not null and cs_quantity !~ '^-?\d+$' then 'cs_quantity:not_integer' end,
      case when cs_wholesale_cost is not null and cs_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'cs_wholesale_cost:not_numeric' end,
      case when cs_list_price is not null and cs_list_price !~ '^-?\d+(\.\d+)?$' then 'cs_list_price:not_numeric' end,
      case when cs_sales_price is not null and cs_sales_price !~ '^-?\d+(\.\d+)?$' then 'cs_sales_price:not_numeric' end,
      case when cs_ext_discount_amt is not null and cs_ext_discount_amt !~ '^-?\d+(\.\d+)?$' then 'cs_ext_discount_amt:not_numeric' end,
      case when cs_ext_sales_price is not null and cs_ext_sales_price !~ '^-?\d+(\.\d+)?$' then 'cs_ext_sales_price:not_numeric' end,
      case when cs_ext_wholesale_cost is not null and cs_ext_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'cs_ext_wholesale_cost:not_numeric' end,
      case when cs_ext_list_price is not null and cs_ext_list_price !~ '^-?\d+(\.\d+)?$' then 'cs_ext_list_price:not_numeric' end,
      case when cs_ext_tax is not null and cs_ext_tax !~ '^-?\d+(\.\d+)?$' then 'cs_ext_tax:not_numeric' end,
      case when cs_coupon_amt is not null and cs_coupon_amt !~ '^-?\d+(\.\d+)?$' then 'cs_coupon_amt:not_numeric' end,
      case when cs_ext_ship_cost is not null and cs_ext_ship_cost !~ '^-?\d+(\.\d+)?$' then 'cs_ext_ship_cost:not_numeric' end,
      case when cs_net_paid is not null and cs_net_paid !~ '^-?\d+(\.\d+)?$' then 'cs_net_paid:not_numeric' end,
      case when cs_net_paid_inc_tax is not null and cs_net_paid_inc_tax !~ '^-?\d+(\.\d+)?$' then 'cs_net_paid_inc_tax:not_numeric' end,
      case when cs_net_paid_inc_ship_tax is not null and cs_net_paid_inc_ship_tax !~ '^-?\d+(\.\d+)?$' then 'cs_net_paid_inc_ship_tax:not_numeric' end,
      case when cs_net_profit is not null and cs_net_profit !~ '^-?\d+(\.\d+)?$' then 'cs_net_profit:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when cs_sold_date_sk is null or cs_sold_date_sk ~ '^-?\d+$' then cs_sold_date_sk::integer end as cs_sold_date_sk,
    case when cs_sold_time_sk is null or cs_sold_time_sk ~ '^-?\d+$' then cs_sold_time_sk::integer end as cs_sold_time_sk,
    case when cs_ship_date_sk is null or cs_ship_date_sk ~ '^-?\d+$' then cs_ship_date_sk::integer end as cs_ship_date_sk,
    case when cs_bill_customer_sk is null or cs_bill_customer_sk ~ '^-?\d+$' then cs_bill_customer_sk::integer end as cs_bill_customer_sk,
    case when cs_bill_cdemo_sk is null or cs_bill_cdemo_sk ~ '^-?\d+$' then cs_bill_cdemo_sk::integer end as cs_bill_cdemo_sk,
    case when cs_bill_hdemo_sk is null or cs_bill_hdemo_sk ~ '^-?\d+$' then cs_bill_hdemo_sk::integer end as cs_bill_hdemo_sk,
    case when cs_bill_addr_sk is null or cs_bill_addr_sk ~ '^-?\d+$' then cs_bill_addr_sk::integer end as cs_bill_addr_sk,
    case when cs_ship_customer_sk is null or cs_ship_customer_sk ~ '^-?\d+$' then cs_ship_customer_sk::integer end as cs_ship_customer_sk,
    case when cs_ship_cdemo_sk is null or cs_ship_cdemo_sk ~ '^-?\d+$' then cs_ship_cdemo_sk::integer end as cs_ship_cdemo_sk,
    case when cs_ship_hdemo_sk is null or cs_ship_hdemo_sk ~ '^-?\d+$' then cs_ship_hdemo_sk::integer end as cs_ship_hdemo_sk,
    case when cs_ship_addr_sk is null or cs_ship_addr_sk ~ '^-?\d+$' then cs_ship_addr_sk::integer end as cs_ship_addr_sk,
    case when cs_call_center_sk is null or cs_call_center_sk ~ '^-?\d+$' then cs_call_center_sk::integer end as cs_call_center_sk,
    case when cs_catalog_page_sk is null or cs_catalog_page_sk ~ '^-?\d+$' then cs_catalog_page_sk::integer end as cs_catalog_page_sk,
    case when cs_ship_mode_sk is null or cs_ship_mode_sk ~ '^-?\d+$' then cs_ship_mode_sk::integer end as cs_ship_mode_sk,
    case when cs_warehouse_sk is null or cs_warehouse_sk ~ '^-?\d+$' then cs_warehouse_sk::integer end as cs_warehouse_sk,
    case when cs_item_sk is null or cs_item_sk ~ '^-?\d+$' then cs_item_sk::integer end as cs_item_sk,
    case when cs_promo_sk is null or cs_promo_sk ~ '^-?\d+$' then cs_promo_sk::integer end as cs_promo_sk,
    case when cs_order_number is null or cs_order_number ~ '^-?\d+$' then cs_order_number::integer end as cs_order_number,
    case when cs_quantity is null or cs_quantity ~ '^-?\d+$' then cs_quantity::integer end as cs_quantity,
    case when cs_wholesale_cost is null or cs_wholesale_cost ~ '^-?\d+(\.\d+)?$' then cs_wholesale_cost::numeric(7,2) end as cs_wholesale_cost,
    case when cs_list_price is null or cs_list_price ~ '^-?\d+(\.\d+)?$' then cs_list_price::numeric(7,2) end as cs_list_price,
    case when cs_sales_price is null or cs_sales_price ~ '^-?\d+(\.\d+)?$' then cs_sales_price::numeric(7,2) end as cs_sales_price,
    case when cs_ext_discount_amt is null or cs_ext_discount_amt ~ '^-?\d+(\.\d+)?$' then cs_ext_discount_amt::numeric(7,2) end as cs_ext_discount_amt,
    case when cs_ext_sales_price is null or cs_ext_sales_price ~ '^-?\d+(\.\d+)?$' then cs_ext_sales_price::numeric(7,2) end as cs_ext_sales_price,
    case when cs_ext_wholesale_cost is null or cs_ext_wholesale_cost ~ '^-?\d+(\.\d+)?$' then cs_ext_wholesale_cost::numeric(7,2) end as cs_ext_wholesale_cost,
    case when cs_ext_list_price is null or cs_ext_list_price ~ '^-?\d+(\.\d+)?$' then cs_ext_list_price::numeric(7,2) end as cs_ext_list_price,
    case when cs_ext_tax is null or cs_ext_tax ~ '^-?\d+(\.\d+)?$' then cs_ext_tax::numeric(7,2) end as cs_ext_tax,
    case when cs_coupon_amt is null or cs_coupon_amt ~ '^-?\d+(\.\d+)?$' then cs_coupon_amt::numeric(7,2) end as cs_coupon_amt,
    case when cs_ext_ship_cost is null or cs_ext_ship_cost ~ '^-?\d+(\.\d+)?$' then cs_ext_ship_cost::numeric(7,2) end as cs_ext_ship_cost,
    case when cs_net_paid is null or cs_net_paid ~ '^-?\d+(\.\d+)?$' then cs_net_paid::numeric(7,2) end as cs_net_paid,
    case when cs_net_paid_inc_tax is null or cs_net_paid_inc_tax ~ '^-?\d+(\.\d+)?$' then cs_net_paid_inc_tax::numeric(7,2) end as cs_net_paid_inc_tax,
    nullif(trim(cs_net_paid_inc_ship), '') as cs_net_paid_inc_ship,
    case when cs_net_paid_inc_ship_tax is null or cs_net_paid_inc_ship_tax ~ '^-?\d+(\.\d+)?$' then cs_net_paid_inc_ship_tax::numeric(7,2) end as cs_net_paid_inc_ship_tax,
    case when cs_net_profit is null or cs_net_profit ~ '^-?\d+(\.\d+)?$' then cs_net_profit::numeric(7,2) end as cs_net_profit
from validated
where array_length(_anomaly_reasons, 1) is null
