-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'store_sales') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when ss_sold_date_sk is not null and ss_sold_date_sk !~ '^-?\d+$' then 'ss_sold_date_sk:not_integer' end,
      case when ss_sold_time_sk is not null and ss_sold_time_sk !~ '^-?\d+$' then 'ss_sold_time_sk:not_integer' end,
      case when ss_item_sk is not null and ss_item_sk !~ '^-?\d+$' then 'ss_item_sk:not_integer' end,
      case when ss_customer_sk is not null and ss_customer_sk !~ '^-?\d+$' then 'ss_customer_sk:not_integer' end,
      case when ss_cdemo_sk is not null and ss_cdemo_sk !~ '^-?\d+$' then 'ss_cdemo_sk:not_integer' end,
      case when ss_hdemo_sk is not null and ss_hdemo_sk !~ '^-?\d+$' then 'ss_hdemo_sk:not_integer' end,
      case when ss_addr_sk is not null and ss_addr_sk !~ '^-?\d+$' then 'ss_addr_sk:not_integer' end,
      case when ss_store_sk is not null and ss_store_sk !~ '^-?\d+$' then 'ss_store_sk:not_integer' end,
      case when ss_promo_sk is not null and ss_promo_sk !~ '^-?\d+$' then 'ss_promo_sk:not_integer' end,
      case when ss_ticket_number is not null and ss_ticket_number !~ '^-?\d+$' then 'ss_ticket_number:not_integer' end,
      case when ss_quantity is not null and ss_quantity !~ '^-?\d+$' then 'ss_quantity:not_integer' end,
      case when ss_wholesale_cost is not null and ss_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'ss_wholesale_cost:not_numeric' end,
      case when ss_list_price is not null and ss_list_price !~ '^-?\d+(\.\d+)?$' then 'ss_list_price:not_numeric' end,
      case when ss_sales_price is not null and ss_sales_price !~ '^-?\d+(\.\d+)?$' then 'ss_sales_price:not_numeric' end,
      case when ss_ext_discount_amt is not null and ss_ext_discount_amt !~ '^-?\d+(\.\d+)?$' then 'ss_ext_discount_amt:not_numeric' end,
      case when ss_ext_sales_price is not null and ss_ext_sales_price !~ '^-?\d+(\.\d+)?$' then 'ss_ext_sales_price:not_numeric' end,
      case when ss_ext_wholesale_cost is not null and ss_ext_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'ss_ext_wholesale_cost:not_numeric' end,
      case when ss_ext_list_price is not null and ss_ext_list_price !~ '^-?\d+(\.\d+)?$' then 'ss_ext_list_price:not_numeric' end,
      case when ss_ext_tax is not null and ss_ext_tax !~ '^-?\d+(\.\d+)?$' then 'ss_ext_tax:not_numeric' end,
      case when ss_coupon_amt is not null and ss_coupon_amt !~ '^-?\d+(\.\d+)?$' then 'ss_coupon_amt:not_numeric' end,
      case when ss_net_paid is not null and ss_net_paid !~ '^-?\d+(\.\d+)?$' then 'ss_net_paid:not_numeric' end,
      case when ss_net_paid_inc_tax is not null and ss_net_paid_inc_tax !~ '^-?\d+(\.\d+)?$' then 'ss_net_paid_inc_tax:not_numeric' end,
      case when ss_net_profit is not null and ss_net_profit !~ '^-?\d+(\.\d+)?$' then 'ss_net_profit:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    ss_sold_date_sk,
    ss_sold_time_sk,
    ss_item_sk,
    ss_customer_sk,
    ss_cdemo_sk,
    ss_hdemo_sk,
    ss_addr_sk,
    ss_store_sk,
    ss_promo_sk,
    ss_ticket_number,
    ss_quantity,
    ss_wholesale_cost,
    ss_list_price,
    ss_sales_price,
    ss_ext_discount_amt,
    ss_ext_sales_price,
    ss_ext_wholesale_cost,
    ss_ext_list_price,
    ss_ext_tax,
    ss_coupon_amt,
    ss_net_paid,
    ss_net_paid_inc_tax,
    ss_net_profit,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
