-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'inventory') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when inv_date_sk is not null and inv_date_sk !~ '^-?\d+$' then 'inv_date_sk:not_integer' end,
      case when inv_item_sk is not null and inv_item_sk !~ '^-?\d+$' then 'inv_item_sk:not_integer' end,
      case when inv_warehouse_sk is not null and inv_warehouse_sk !~ '^-?\d+$' then 'inv_warehouse_sk:not_integer' end,
      case when inv_quantity_on_hand is not null and inv_quantity_on_hand !~ '^-?\d+$' then 'inv_quantity_on_hand:not_integer' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when inv_date_sk is null or inv_date_sk ~ '^-?\d+$' then inv_date_sk::integer end as inv_date_sk,
    case when inv_item_sk is null or inv_item_sk ~ '^-?\d+$' then inv_item_sk::integer end as inv_item_sk,
    case when inv_warehouse_sk is null or inv_warehouse_sk ~ '^-?\d+$' then inv_warehouse_sk::integer end as inv_warehouse_sk,
    case when inv_quantity_on_hand is null or inv_quantity_on_hand ~ '^-?\d+$' then inv_quantity_on_hand::integer end as inv_quantity_on_hand
from validated
where array_length(_anomaly_reasons, 1) is null
