-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'store_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when sr_returned_date_sk is not null and sr_returned_date_sk !~ '^-?\d+$' then 'sr_returned_date_sk:not_integer' end,
      case when sr_return_time_sk is not null and sr_return_time_sk !~ '^-?\d+$' then 'sr_return_time_sk:not_integer' end,
      case when sr_item_sk is not null and sr_item_sk !~ '^-?\d+$' then 'sr_item_sk:not_integer' end,
      case when sr_customer_sk is not null and sr_customer_sk !~ '^-?\d+$' then 'sr_customer_sk:not_integer' end,
      case when sr_cdemo_sk is not null and sr_cdemo_sk !~ '^-?\d+$' then 'sr_cdemo_sk:not_integer' end,
      case when sr_hdemo_sk is not null and sr_hdemo_sk !~ '^-?\d+$' then 'sr_hdemo_sk:not_integer' end,
      case when sr_addr_sk is not null and sr_addr_sk !~ '^-?\d+$' then 'sr_addr_sk:not_integer' end,
      case when sr_store_sk is not null and sr_store_sk !~ '^-?\d+$' then 'sr_store_sk:not_integer' end,
      case when sr_reason_sk is not null and sr_reason_sk !~ '^-?\d+$' then 'sr_reason_sk:not_integer' end,
      case when sr_ticket_number is not null and sr_ticket_number !~ '^-?\d+$' then 'sr_ticket_number:not_integer' end,
      case when sr_return_quantity is not null and sr_return_quantity !~ '^-?\d+$' then 'sr_return_quantity:not_integer' end,
      case when sr_return_amt is not null and sr_return_amt !~ '^-?\d+(\.\d+)?$' then 'sr_return_amt:not_numeric' end,
      case when sr_return_tax is not null and sr_return_tax !~ '^-?\d+(\.\d+)?$' then 'sr_return_tax:not_numeric' end,
      case when sr_return_amt_inc_tax is not null and sr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'sr_return_amt_inc_tax:not_numeric' end,
      case when sr_fee is not null and sr_fee !~ '^-?\d+(\.\d+)?$' then 'sr_fee:not_numeric' end,
      case when sr_return_ship_cost is not null and sr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'sr_return_ship_cost:not_numeric' end,
      case when sr_refunded_cash is not null and sr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'sr_refunded_cash:not_numeric' end,
      case when sr_reversed_charge is not null and sr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'sr_reversed_charge:not_numeric' end,
      case when sr_store_credit is not null and sr_store_credit !~ '^-?\d+(\.\d+)?$' then 'sr_store_credit:not_numeric' end,
      case when sr_net_loss is not null and sr_net_loss !~ '^-?\d+(\.\d+)?$' then 'sr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    sr_returned_date_sk,
    sr_return_time_sk,
    sr_item_sk,
    sr_customer_sk,
    sr_cdemo_sk,
    sr_hdemo_sk,
    sr_addr_sk,
    sr_store_sk,
    sr_reason_sk,
    sr_ticket_number,
    sr_return_quantity,
    sr_return_amt,
    sr_return_tax,
    sr_return_amt_inc_tax,
    sr_fee,
    sr_return_ship_cost,
    sr_refunded_cash,
    sr_reversed_charge,
    sr_store_credit,
    sr_net_loss,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
