-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'store_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when sr_returned_date_sk is not null and sr_returned_date_sk !~ '^-?\d+$' then 'sr_returned_date_sk:not_integer' end,
      case when sr_return_time_sk is not null and sr_return_time_sk !~ '^-?\d+$' then 'sr_return_time_sk:not_integer' end,
      case when sr_item_sk is not null and sr_item_sk !~ '^-?\d+$' then 'sr_item_sk:not_integer' end,
      case when sr_customer_sk is not null and sr_customer_sk !~ '^-?\d+$' then 'sr_customer_sk:not_integer' end,
      case when sr_cdemo_sk is not null and sr_cdemo_sk !~ '^-?\d+$' then 'sr_cdemo_sk:not_integer' end,
      case when sr_hdemo_sk is not null and sr_hdemo_sk !~ '^-?\d+$' then 'sr_hdemo_sk:not_integer' end,
      case when sr_addr_sk is not null and sr_addr_sk !~ '^-?\d+$' then 'sr_addr_sk:not_integer' end,
      case when sr_store_sk is not null and sr_store_sk !~ '^-?\d+$' then 'sr_store_sk:not_integer' end,
      case when sr_reason_sk is not null and sr_reason_sk !~ '^-?\d+$' then 'sr_reason_sk:not_integer' end,
      case when sr_ticket_number is not null and sr_ticket_number !~ '^-?\d+$' then 'sr_ticket_number:not_integer' end,
      case when sr_return_quantity is not null and sr_return_quantity !~ '^-?\d+$' then 'sr_return_quantity:not_integer' end,
      case when sr_return_amt is not null and sr_return_amt !~ '^-?\d+(\.\d+)?$' then 'sr_return_amt:not_numeric' end,
      case when sr_return_tax is not null and sr_return_tax !~ '^-?\d+(\.\d+)?$' then 'sr_return_tax:not_numeric' end,
      case when sr_return_amt_inc_tax is not null and sr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'sr_return_amt_inc_tax:not_numeric' end,
      case when sr_fee is not null and sr_fee !~ '^-?\d+(\.\d+)?$' then 'sr_fee:not_numeric' end,
      case when sr_return_ship_cost is not null and sr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'sr_return_ship_cost:not_numeric' end,
      case when sr_refunded_cash is not null and sr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'sr_refunded_cash:not_numeric' end,
      case when sr_reversed_charge is not null and sr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'sr_reversed_charge:not_numeric' end,
      case when sr_store_credit is not null and sr_store_credit !~ '^-?\d+(\.\d+)?$' then 'sr_store_credit:not_numeric' end,
      case when sr_net_loss is not null and sr_net_loss !~ '^-?\d+(\.\d+)?$' then 'sr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when sr_returned_date_sk is null or sr_returned_date_sk ~ '^-?\d+$' then sr_returned_date_sk::integer end as sr_returned_date_sk,
    case when sr_return_time_sk is null or sr_return_time_sk ~ '^-?\d+$' then sr_return_time_sk::integer end as sr_return_time_sk,
    case when sr_item_sk is null or sr_item_sk ~ '^-?\d+$' then sr_item_sk::integer end as sr_item_sk,
    case when sr_customer_sk is null or sr_customer_sk ~ '^-?\d+$' then sr_customer_sk::integer end as sr_customer_sk,
    case when sr_cdemo_sk is null or sr_cdemo_sk ~ '^-?\d+$' then sr_cdemo_sk::integer end as sr_cdemo_sk,
    case when sr_hdemo_sk is null or sr_hdemo_sk ~ '^-?\d+$' then sr_hdemo_sk::integer end as sr_hdemo_sk,
    case when sr_addr_sk is null or sr_addr_sk ~ '^-?\d+$' then sr_addr_sk::integer end as sr_addr_sk,
    case when sr_store_sk is null or sr_store_sk ~ '^-?\d+$' then sr_store_sk::integer end as sr_store_sk,
    case when sr_reason_sk is null or sr_reason_sk ~ '^-?\d+$' then sr_reason_sk::integer end as sr_reason_sk,
    case when sr_ticket_number is null or sr_ticket_number ~ '^-?\d+$' then sr_ticket_number::integer end as sr_ticket_number,
    case when sr_return_quantity is null or sr_return_quantity ~ '^-?\d+$' then sr_return_quantity::integer end as sr_return_quantity,
    case when sr_return_amt is null or sr_return_amt ~ '^-?\d+(\.\d+)?$' then sr_return_amt::numeric(7,2) end as sr_return_amt,
    case when sr_return_tax is null or sr_return_tax ~ '^-?\d+(\.\d+)?$' then sr_return_tax::numeric(7,2) end as sr_return_tax,
    case when sr_return_amt_inc_tax is null or sr_return_amt_inc_tax ~ '^-?\d+(\.\d+)?$' then sr_return_amt_inc_tax::numeric(7,2) end as sr_return_amt_inc_tax,
    case when sr_fee is null or sr_fee ~ '^-?\d+(\.\d+)?$' then sr_fee::numeric(7,2) end as sr_fee,
    case when sr_return_ship_cost is null or sr_return_ship_cost ~ '^-?\d+(\.\d+)?$' then sr_return_ship_cost::numeric(7,2) end as sr_return_ship_cost,
    case when sr_refunded_cash is null or sr_refunded_cash ~ '^-?\d+(\.\d+)?$' then sr_refunded_cash::numeric(7,2) end as sr_refunded_cash,
    case when sr_reversed_charge is null or sr_reversed_charge ~ '^-?\d+(\.\d+)?$' then sr_reversed_charge::numeric(7,2) end as sr_reversed_charge,
    case when sr_store_credit is null or sr_store_credit ~ '^-?\d+(\.\d+)?$' then sr_store_credit::numeric(7,2) end as sr_store_credit,
    case when sr_net_loss is null or sr_net_loss ~ '^-?\d+(\.\d+)?$' then sr_net_loss::numeric(7,2) end as sr_net_loss
from validated
where array_length(_anomaly_reasons, 1) is null
