-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'catalog_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cr_returned_date_sk is not null and cr_returned_date_sk !~ '^-?\d+$' then 'cr_returned_date_sk:not_integer' end,
      case when cr_returned_time_sk is not null and cr_returned_time_sk !~ '^-?\d+$' then 'cr_returned_time_sk:not_integer' end,
      case when cr_item_sk is not null and cr_item_sk !~ '^-?\d+$' then 'cr_item_sk:not_integer' end,
      case when cr_refunded_customer_sk is not null and cr_refunded_customer_sk !~ '^-?\d+$' then 'cr_refunded_customer_sk:not_integer' end,
      case when cr_refunded_cdemo_sk is not null and cr_refunded_cdemo_sk !~ '^-?\d+$' then 'cr_refunded_cdemo_sk:not_integer' end,
      case when cr_refunded_hdemo_sk is not null and cr_refunded_hdemo_sk !~ '^-?\d+$' then 'cr_refunded_hdemo_sk:not_integer' end,
      case when cr_refunded_addr_sk is not null and cr_refunded_addr_sk !~ '^-?\d+$' then 'cr_refunded_addr_sk:not_integer' end,
      case when cr_returning_customer_sk is not null and cr_returning_customer_sk !~ '^-?\d+$' then 'cr_returning_customer_sk:not_integer' end,
      case when cr_returning_cdemo_sk is not null and cr_returning_cdemo_sk !~ '^-?\d+$' then 'cr_returning_cdemo_sk:not_integer' end,
      case when cr_returning_hdemo_sk is not null and cr_returning_hdemo_sk !~ '^-?\d+$' then 'cr_returning_hdemo_sk:not_integer' end,
      case when cr_returning_addr_sk is not null and cr_returning_addr_sk !~ '^-?\d+$' then 'cr_returning_addr_sk:not_integer' end,
      case when cr_call_center_sk is not null and cr_call_center_sk !~ '^-?\d+$' then 'cr_call_center_sk:not_integer' end,
      case when cr_catalog_page_sk is not null and cr_catalog_page_sk !~ '^-?\d+$' then 'cr_catalog_page_sk:not_integer' end,
      case when cr_ship_mode_sk is not null and cr_ship_mode_sk !~ '^-?\d+$' then 'cr_ship_mode_sk:not_integer' end,
      case when cr_warehouse_sk is not null and cr_warehouse_sk !~ '^-?\d+$' then 'cr_warehouse_sk:not_integer' end,
      case when cr_reason_sk is not null and cr_reason_sk !~ '^-?\d+$' then 'cr_reason_sk:not_integer' end,
      case when cr_order_number is not null and cr_order_number !~ '^-?\d+$' then 'cr_order_number:not_integer' end,
      case when cr_return_quantity is not null and cr_return_quantity !~ '^-?\d+$' then 'cr_return_quantity:not_integer' end,
      case when cr_return_amount is not null and cr_return_amount !~ '^-?\d+(\.\d+)?$' then 'cr_return_amount:not_numeric' end,
      case when cr_return_tax is not null and cr_return_tax !~ '^-?\d+(\.\d+)?$' then 'cr_return_tax:not_numeric' end,
      case when cr_return_amt_inc_tax is not null and cr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'cr_return_amt_inc_tax:not_numeric' end,
      case when cr_fee is not null and cr_fee !~ '^-?\d+(\.\d+)?$' then 'cr_fee:not_numeric' end,
      case when cr_return_ship_cost is not null and cr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'cr_return_ship_cost:not_numeric' end,
      case when cr_refunded_cash is not null and cr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'cr_refunded_cash:not_numeric' end,
      case when cr_reversed_charge is not null and cr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'cr_reversed_charge:not_numeric' end,
      case when cr_store_credit is not null and cr_store_credit !~ '^-?\d+(\.\d+)?$' then 'cr_store_credit:not_numeric' end,
      case when cr_net_loss is not null and cr_net_loss !~ '^-?\d+(\.\d+)?$' then 'cr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when cr_returned_date_sk is null or cr_returned_date_sk ~ '^-?\d+$' then cr_returned_date_sk::integer end as cr_returned_date_sk,
    case when cr_returned_time_sk is null or cr_returned_time_sk ~ '^-?\d+$' then cr_returned_time_sk::integer end as cr_returned_time_sk,
    case when cr_item_sk is null or cr_item_sk ~ '^-?\d+$' then cr_item_sk::integer end as cr_item_sk,
    case when cr_refunded_customer_sk is null or cr_refunded_customer_sk ~ '^-?\d+$' then cr_refunded_customer_sk::integer end as cr_refunded_customer_sk,
    case when cr_refunded_cdemo_sk is null or cr_refunded_cdemo_sk ~ '^-?\d+$' then cr_refunded_cdemo_sk::integer end as cr_refunded_cdemo_sk,
    case when cr_refunded_hdemo_sk is null or cr_refunded_hdemo_sk ~ '^-?\d+$' then cr_refunded_hdemo_sk::integer end as cr_refunded_hdemo_sk,
    case when cr_refunded_addr_sk is null or cr_refunded_addr_sk ~ '^-?\d+$' then cr_refunded_addr_sk::integer end as cr_refunded_addr_sk,
    case when cr_returning_customer_sk is null or cr_returning_customer_sk ~ '^-?\d+$' then cr_returning_customer_sk::integer end as cr_returning_customer_sk,
    case when cr_returning_cdemo_sk is null or cr_returning_cdemo_sk ~ '^-?\d+$' then cr_returning_cdemo_sk::integer end as cr_returning_cdemo_sk,
    case when cr_returning_hdemo_sk is null or cr_returning_hdemo_sk ~ '^-?\d+$' then cr_returning_hdemo_sk::integer end as cr_returning_hdemo_sk,
    case when cr_returning_addr_sk is null or cr_returning_addr_sk ~ '^-?\d+$' then cr_returning_addr_sk::integer end as cr_returning_addr_sk,
    case when cr_call_center_sk is null or cr_call_center_sk ~ '^-?\d+$' then cr_call_center_sk::integer end as cr_call_center_sk,
    case when cr_catalog_page_sk is null or cr_catalog_page_sk ~ '^-?\d+$' then cr_catalog_page_sk::integer end as cr_catalog_page_sk,
    case when cr_ship_mode_sk is null or cr_ship_mode_sk ~ '^-?\d+$' then cr_ship_mode_sk::integer end as cr_ship_mode_sk,
    case when cr_warehouse_sk is null or cr_warehouse_sk ~ '^-?\d+$' then cr_warehouse_sk::integer end as cr_warehouse_sk,
    case when cr_reason_sk is null or cr_reason_sk ~ '^-?\d+$' then cr_reason_sk::integer end as cr_reason_sk,
    case when cr_order_number is null or cr_order_number ~ '^-?\d+$' then cr_order_number::integer end as cr_order_number,
    case when cr_return_quantity is null or cr_return_quantity ~ '^-?\d+$' then cr_return_quantity::integer end as cr_return_quantity,
    case when cr_return_amount is null or cr_return_amount ~ '^-?\d+(\.\d+)?$' then cr_return_amount::numeric(7,2) end as cr_return_amount,
    case when cr_return_tax is null or cr_return_tax ~ '^-?\d+(\.\d+)?$' then cr_return_tax::numeric(7,2) end as cr_return_tax,
    case when cr_return_amt_inc_tax is null or cr_return_amt_inc_tax ~ '^-?\d+(\.\d+)?$' then cr_return_amt_inc_tax::numeric(7,2) end as cr_return_amt_inc_tax,
    case when cr_fee is null or cr_fee ~ '^-?\d+(\.\d+)?$' then cr_fee::numeric(7,2) end as cr_fee,
    case when cr_return_ship_cost is null or cr_return_ship_cost ~ '^-?\d+(\.\d+)?$' then cr_return_ship_cost::numeric(7,2) end as cr_return_ship_cost,
    case when cr_refunded_cash is null or cr_refunded_cash ~ '^-?\d+(\.\d+)?$' then cr_refunded_cash::numeric(7,2) end as cr_refunded_cash,
    case when cr_reversed_charge is null or cr_reversed_charge ~ '^-?\d+(\.\d+)?$' then cr_reversed_charge::numeric(7,2) end as cr_reversed_charge,
    case when cr_store_credit is null or cr_store_credit ~ '^-?\d+(\.\d+)?$' then cr_store_credit::numeric(7,2) end as cr_store_credit,
    case when cr_net_loss is null or cr_net_loss ~ '^-?\d+(\.\d+)?$' then cr_net_loss::numeric(7,2) end as cr_net_loss
from validated
where array_length(_anomaly_reasons, 1) is null
