-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when wr_returned_date_sk is not null and wr_returned_date_sk !~ '^-?\d+$' then 'wr_returned_date_sk:not_integer' end,
      case when wr_returned_time_sk is not null and wr_returned_time_sk !~ '^-?\d+$' then 'wr_returned_time_sk:not_integer' end,
      case when wr_item_sk is not null and wr_item_sk !~ '^-?\d+$' then 'wr_item_sk:not_integer' end,
      case when wr_refunded_customer_sk is not null and wr_refunded_customer_sk !~ '^-?\d+$' then 'wr_refunded_customer_sk:not_integer' end,
      case when wr_refunded_cdemo_sk is not null and wr_refunded_cdemo_sk !~ '^-?\d+$' then 'wr_refunded_cdemo_sk:not_integer' end,
      case when wr_refunded_hdemo_sk is not null and wr_refunded_hdemo_sk !~ '^-?\d+$' then 'wr_refunded_hdemo_sk:not_integer' end,
      case when wr_refunded_addr_sk is not null and wr_refunded_addr_sk !~ '^-?\d+$' then 'wr_refunded_addr_sk:not_integer' end,
      case when wr_returning_customer_sk is not null and wr_returning_customer_sk !~ '^-?\d+$' then 'wr_returning_customer_sk:not_integer' end,
      case when wr_returning_cdemo_sk is not null and wr_returning_cdemo_sk !~ '^-?\d+$' then 'wr_returning_cdemo_sk:not_integer' end,
      case when wr_returning_hdemo_sk is not null and wr_returning_hdemo_sk !~ '^-?\d+$' then 'wr_returning_hdemo_sk:not_integer' end,
      case when wr_returning_addr_sk is not null and wr_returning_addr_sk !~ '^-?\d+$' then 'wr_returning_addr_sk:not_integer' end,
      case when wr_web_page_sk is not null and wr_web_page_sk !~ '^-?\d+$' then 'wr_web_page_sk:not_integer' end,
      case when wr_reason_sk is not null and wr_reason_sk !~ '^-?\d+$' then 'wr_reason_sk:not_integer' end,
      case when wr_order_number is not null and wr_order_number !~ '^-?\d+$' then 'wr_order_number:not_integer' end,
      case when wr_return_quantity is not null and wr_return_quantity !~ '^-?\d+$' then 'wr_return_quantity:not_integer' end,
      case when wr_return_amt is not null and wr_return_amt !~ '^-?\d+(\.\d+)?$' then 'wr_return_amt:not_numeric' end,
      case when wr_return_tax is not null and wr_return_tax !~ '^-?\d+(\.\d+)?$' then 'wr_return_tax:not_numeric' end,
      case when wr_return_amt_inc_tax is not null and wr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'wr_return_amt_inc_tax:not_numeric' end,
      case when wr_fee is not null and wr_fee !~ '^-?\d+(\.\d+)?$' then 'wr_fee:not_numeric' end,
      case when wr_return_ship_cost is not null and wr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'wr_return_ship_cost:not_numeric' end,
      case when wr_refunded_cash is not null and wr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'wr_refunded_cash:not_numeric' end,
      case when wr_reversed_charge is not null and wr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'wr_reversed_charge:not_numeric' end,
      case when wr_account_credit is not null and wr_account_credit !~ '^-?\d+(\.\d+)?$' then 'wr_account_credit:not_numeric' end,
      case when wr_net_loss is not null and wr_net_loss !~ '^-?\d+(\.\d+)?$' then 'wr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    case when wr_returned_date_sk is null or wr_returned_date_sk ~ '^-?\d+$' then wr_returned_date_sk::integer end as wr_returned_date_sk,
    case when wr_returned_time_sk is null or wr_returned_time_sk ~ '^-?\d+$' then wr_returned_time_sk::integer end as wr_returned_time_sk,
    case when wr_item_sk is null or wr_item_sk ~ '^-?\d+$' then wr_item_sk::integer end as wr_item_sk,
    case when wr_refunded_customer_sk is null or wr_refunded_customer_sk ~ '^-?\d+$' then wr_refunded_customer_sk::integer end as wr_refunded_customer_sk,
    case when wr_refunded_cdemo_sk is null or wr_refunded_cdemo_sk ~ '^-?\d+$' then wr_refunded_cdemo_sk::integer end as wr_refunded_cdemo_sk,
    case when wr_refunded_hdemo_sk is null or wr_refunded_hdemo_sk ~ '^-?\d+$' then wr_refunded_hdemo_sk::integer end as wr_refunded_hdemo_sk,
    case when wr_refunded_addr_sk is null or wr_refunded_addr_sk ~ '^-?\d+$' then wr_refunded_addr_sk::integer end as wr_refunded_addr_sk,
    case when wr_returning_customer_sk is null or wr_returning_customer_sk ~ '^-?\d+$' then wr_returning_customer_sk::integer end as wr_returning_customer_sk,
    case when wr_returning_cdemo_sk is null or wr_returning_cdemo_sk ~ '^-?\d+$' then wr_returning_cdemo_sk::integer end as wr_returning_cdemo_sk,
    case when wr_returning_hdemo_sk is null or wr_returning_hdemo_sk ~ '^-?\d+$' then wr_returning_hdemo_sk::integer end as wr_returning_hdemo_sk,
    case when wr_returning_addr_sk is null or wr_returning_addr_sk ~ '^-?\d+$' then wr_returning_addr_sk::integer end as wr_returning_addr_sk,
    case when wr_web_page_sk is null or wr_web_page_sk ~ '^-?\d+$' then wr_web_page_sk::integer end as wr_web_page_sk,
    case when wr_reason_sk is null or wr_reason_sk ~ '^-?\d+$' then wr_reason_sk::integer end as wr_reason_sk,
    case when wr_order_number is null or wr_order_number ~ '^-?\d+$' then wr_order_number::integer end as wr_order_number,
    case when wr_return_quantity is null or wr_return_quantity ~ '^-?\d+$' then wr_return_quantity::integer end as wr_return_quantity,
    case when wr_return_amt is null or wr_return_amt ~ '^-?\d+(\.\d+)?$' then wr_return_amt::numeric(7,2) end as wr_return_amt,
    case when wr_return_tax is null or wr_return_tax ~ '^-?\d+(\.\d+)?$' then wr_return_tax::numeric(7,2) end as wr_return_tax,
    case when wr_return_amt_inc_tax is null or wr_return_amt_inc_tax ~ '^-?\d+(\.\d+)?$' then wr_return_amt_inc_tax::numeric(7,2) end as wr_return_amt_inc_tax,
    case when wr_fee is null or wr_fee ~ '^-?\d+(\.\d+)?$' then wr_fee::numeric(7,2) end as wr_fee,
    case when wr_return_ship_cost is null or wr_return_ship_cost ~ '^-?\d+(\.\d+)?$' then wr_return_ship_cost::numeric(7,2) end as wr_return_ship_cost,
    case when wr_refunded_cash is null or wr_refunded_cash ~ '^-?\d+(\.\d+)?$' then wr_refunded_cash::numeric(7,2) end as wr_refunded_cash,
    case when wr_reversed_charge is null or wr_reversed_charge ~ '^-?\d+(\.\d+)?$' then wr_reversed_charge::numeric(7,2) end as wr_reversed_charge,
    case when wr_account_credit is null or wr_account_credit ~ '^-?\d+(\.\d+)?$' then wr_account_credit::numeric(7,2) end as wr_account_credit,
    case when wr_net_loss is null or wr_net_loss ~ '^-?\d+(\.\d+)?$' then wr_net_loss::numeric(7,2) end as wr_net_loss
from validated
where array_length(_anomaly_reasons, 1) is null
