-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'catalog_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when cr_returned_date_sk is not null and cr_returned_date_sk !~ '^-?\d+$' then 'cr_returned_date_sk:not_integer' end,
      case when cr_returned_time_sk is not null and cr_returned_time_sk !~ '^-?\d+$' then 'cr_returned_time_sk:not_integer' end,
      case when cr_item_sk is not null and cr_item_sk !~ '^-?\d+$' then 'cr_item_sk:not_integer' end,
      case when cr_refunded_customer_sk is not null and cr_refunded_customer_sk !~ '^-?\d+$' then 'cr_refunded_customer_sk:not_integer' end,
      case when cr_refunded_cdemo_sk is not null and cr_refunded_cdemo_sk !~ '^-?\d+$' then 'cr_refunded_cdemo_sk:not_integer' end,
      case when cr_refunded_hdemo_sk is not null and cr_refunded_hdemo_sk !~ '^-?\d+$' then 'cr_refunded_hdemo_sk:not_integer' end,
      case when cr_refunded_addr_sk is not null and cr_refunded_addr_sk !~ '^-?\d+$' then 'cr_refunded_addr_sk:not_integer' end,
      case when cr_returning_customer_sk is not null and cr_returning_customer_sk !~ '^-?\d+$' then 'cr_returning_customer_sk:not_integer' end,
      case when cr_returning_cdemo_sk is not null and cr_returning_cdemo_sk !~ '^-?\d+$' then 'cr_returning_cdemo_sk:not_integer' end,
      case when cr_returning_hdemo_sk is not null and cr_returning_hdemo_sk !~ '^-?\d+$' then 'cr_returning_hdemo_sk:not_integer' end,
      case when cr_returning_addr_sk is not null and cr_returning_addr_sk !~ '^-?\d+$' then 'cr_returning_addr_sk:not_integer' end,
      case when cr_call_center_sk is not null and cr_call_center_sk !~ '^-?\d+$' then 'cr_call_center_sk:not_integer' end,
      case when cr_catalog_page_sk is not null and cr_catalog_page_sk !~ '^-?\d+$' then 'cr_catalog_page_sk:not_integer' end,
      case when cr_ship_mode_sk is not null and cr_ship_mode_sk !~ '^-?\d+$' then 'cr_ship_mode_sk:not_integer' end,
      case when cr_warehouse_sk is not null and cr_warehouse_sk !~ '^-?\d+$' then 'cr_warehouse_sk:not_integer' end,
      case when cr_reason_sk is not null and cr_reason_sk !~ '^-?\d+$' then 'cr_reason_sk:not_integer' end,
      case when cr_order_number is not null and cr_order_number !~ '^-?\d+$' then 'cr_order_number:not_integer' end,
      case when cr_return_quantity is not null and cr_return_quantity !~ '^-?\d+$' then 'cr_return_quantity:not_integer' end,
      case when cr_return_amount is not null and cr_return_amount !~ '^-?\d+(\.\d+)?$' then 'cr_return_amount:not_numeric' end,
      case when cr_return_tax is not null and cr_return_tax !~ '^-?\d+(\.\d+)?$' then 'cr_return_tax:not_numeric' end,
      case when cr_return_amt_inc_tax is not null and cr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'cr_return_amt_inc_tax:not_numeric' end,
      case when cr_fee is not null and cr_fee !~ '^-?\d+(\.\d+)?$' then 'cr_fee:not_numeric' end,
      case when cr_return_ship_cost is not null and cr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'cr_return_ship_cost:not_numeric' end,
      case when cr_refunded_cash is not null and cr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'cr_refunded_cash:not_numeric' end,
      case when cr_reversed_charge is not null and cr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'cr_reversed_charge:not_numeric' end,
      case when cr_store_credit is not null and cr_store_credit !~ '^-?\d+(\.\d+)?$' then 'cr_store_credit:not_numeric' end,
      case when cr_net_loss is not null and cr_net_loss !~ '^-?\d+(\.\d+)?$' then 'cr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    cr_returned_date_sk,
    cr_returned_time_sk,
    cr_item_sk,
    cr_refunded_customer_sk,
    cr_refunded_cdemo_sk,
    cr_refunded_hdemo_sk,
    cr_refunded_addr_sk,
    cr_returning_customer_sk,
    cr_returning_cdemo_sk,
    cr_returning_hdemo_sk,
    cr_returning_addr_sk,
    cr_call_center_sk,
    cr_catalog_page_sk,
    cr_ship_mode_sk,
    cr_warehouse_sk,
    cr_reason_sk,
    cr_order_number,
    cr_return_quantity,
    cr_return_amount,
    cr_return_tax,
    cr_return_amt_inc_tax,
    cr_fee,
    cr_return_ship_cost,
    cr_refunded_cash,
    cr_reversed_charge,
    cr_store_credit,
    cr_net_loss,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
