-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_returns') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when wr_returned_date_sk is not null and wr_returned_date_sk !~ '^-?\d+$' then 'wr_returned_date_sk:not_integer' end,
      case when wr_returned_time_sk is not null and wr_returned_time_sk !~ '^-?\d+$' then 'wr_returned_time_sk:not_integer' end,
      case when wr_item_sk is not null and wr_item_sk !~ '^-?\d+$' then 'wr_item_sk:not_integer' end,
      case when wr_refunded_customer_sk is not null and wr_refunded_customer_sk !~ '^-?\d+$' then 'wr_refunded_customer_sk:not_integer' end,
      case when wr_refunded_cdemo_sk is not null and wr_refunded_cdemo_sk !~ '^-?\d+$' then 'wr_refunded_cdemo_sk:not_integer' end,
      case when wr_refunded_hdemo_sk is not null and wr_refunded_hdemo_sk !~ '^-?\d+$' then 'wr_refunded_hdemo_sk:not_integer' end,
      case when wr_refunded_addr_sk is not null and wr_refunded_addr_sk !~ '^-?\d+$' then 'wr_refunded_addr_sk:not_integer' end,
      case when wr_returning_customer_sk is not null and wr_returning_customer_sk !~ '^-?\d+$' then 'wr_returning_customer_sk:not_integer' end,
      case when wr_returning_cdemo_sk is not null and wr_returning_cdemo_sk !~ '^-?\d+$' then 'wr_returning_cdemo_sk:not_integer' end,
      case when wr_returning_hdemo_sk is not null and wr_returning_hdemo_sk !~ '^-?\d+$' then 'wr_returning_hdemo_sk:not_integer' end,
      case when wr_returning_addr_sk is not null and wr_returning_addr_sk !~ '^-?\d+$' then 'wr_returning_addr_sk:not_integer' end,
      case when wr_web_page_sk is not null and wr_web_page_sk !~ '^-?\d+$' then 'wr_web_page_sk:not_integer' end,
      case when wr_reason_sk is not null and wr_reason_sk !~ '^-?\d+$' then 'wr_reason_sk:not_integer' end,
      case when wr_order_number is not null and wr_order_number !~ '^-?\d+$' then 'wr_order_number:not_integer' end,
      case when wr_return_quantity is not null and wr_return_quantity !~ '^-?\d+$' then 'wr_return_quantity:not_integer' end,
      case when wr_return_amt is not null and wr_return_amt !~ '^-?\d+(\.\d+)?$' then 'wr_return_amt:not_numeric' end,
      case when wr_return_tax is not null and wr_return_tax !~ '^-?\d+(\.\d+)?$' then 'wr_return_tax:not_numeric' end,
      case when wr_return_amt_inc_tax is not null and wr_return_amt_inc_tax !~ '^-?\d+(\.\d+)?$' then 'wr_return_amt_inc_tax:not_numeric' end,
      case when wr_fee is not null and wr_fee !~ '^-?\d+(\.\d+)?$' then 'wr_fee:not_numeric' end,
      case when wr_return_ship_cost is not null and wr_return_ship_cost !~ '^-?\d+(\.\d+)?$' then 'wr_return_ship_cost:not_numeric' end,
      case when wr_refunded_cash is not null and wr_refunded_cash !~ '^-?\d+(\.\d+)?$' then 'wr_refunded_cash:not_numeric' end,
      case when wr_reversed_charge is not null and wr_reversed_charge !~ '^-?\d+(\.\d+)?$' then 'wr_reversed_charge:not_numeric' end,
      case when wr_account_credit is not null and wr_account_credit !~ '^-?\d+(\.\d+)?$' then 'wr_account_credit:not_numeric' end,
      case when wr_net_loss is not null and wr_net_loss !~ '^-?\d+(\.\d+)?$' then 'wr_net_loss:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    wr_returned_date_sk,
    wr_returned_time_sk,
    wr_item_sk,
    wr_refunded_customer_sk,
    wr_refunded_cdemo_sk,
    wr_refunded_hdemo_sk,
    wr_refunded_addr_sk,
    wr_returning_customer_sk,
    wr_returning_cdemo_sk,
    wr_returning_hdemo_sk,
    wr_returning_addr_sk,
    wr_web_page_sk,
    wr_reason_sk,
    wr_order_number,
    wr_return_quantity,
    wr_return_amt,
    wr_return_tax,
    wr_return_amt_inc_tax,
    wr_fee,
    wr_return_ship_cost,
    wr_refunded_cash,
    wr_reversed_charge,
    wr_account_credit,
    wr_net_loss,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
