-- GENERATED by scripts/generate_silver_models.py - do not edit by hand.
{{ config(materialized='table', schema='silver') }}

with raw as (
  select * from {{ source('bronze', 'web_sales') }}
),
validated as (
  select
    raw.*,
    array_remove(array[
      case when ws_sold_date_sk is not null and ws_sold_date_sk !~ '^-?\d+$' then 'ws_sold_date_sk:not_integer' end,
      case when ws_sold_time_sk is not null and ws_sold_time_sk !~ '^-?\d+$' then 'ws_sold_time_sk:not_integer' end,
      case when ws_ship_date_sk is not null and ws_ship_date_sk !~ '^-?\d+$' then 'ws_ship_date_sk:not_integer' end,
      case when ws_item_sk is not null and ws_item_sk !~ '^-?\d+$' then 'ws_item_sk:not_integer' end,
      case when ws_bill_customer_sk is not null and ws_bill_customer_sk !~ '^-?\d+$' then 'ws_bill_customer_sk:not_integer' end,
      case when ws_bill_cdemo_sk is not null and ws_bill_cdemo_sk !~ '^-?\d+$' then 'ws_bill_cdemo_sk:not_integer' end,
      case when ws_bill_hdemo_sk is not null and ws_bill_hdemo_sk !~ '^-?\d+$' then 'ws_bill_hdemo_sk:not_integer' end,
      case when ws_bill_addr_sk is not null and ws_bill_addr_sk !~ '^-?\d+$' then 'ws_bill_addr_sk:not_integer' end,
      case when ws_ship_customer_sk is not null and ws_ship_customer_sk !~ '^-?\d+$' then 'ws_ship_customer_sk:not_integer' end,
      case when ws_ship_cdemo_sk is not null and ws_ship_cdemo_sk !~ '^-?\d+$' then 'ws_ship_cdemo_sk:not_integer' end,
      case when ws_ship_hdemo_sk is not null and ws_ship_hdemo_sk !~ '^-?\d+$' then 'ws_ship_hdemo_sk:not_integer' end,
      case when ws_ship_addr_sk is not null and ws_ship_addr_sk !~ '^-?\d+$' then 'ws_ship_addr_sk:not_integer' end,
      case when ws_web_page_sk is not null and ws_web_page_sk !~ '^-?\d+$' then 'ws_web_page_sk:not_integer' end,
      case when ws_web_site_sk is not null and ws_web_site_sk !~ '^-?\d+$' then 'ws_web_site_sk:not_integer' end,
      case when ws_ship_mode_sk is not null and ws_ship_mode_sk !~ '^-?\d+$' then 'ws_ship_mode_sk:not_integer' end,
      case when ws_warehouse_sk is not null and ws_warehouse_sk !~ '^-?\d+$' then 'ws_warehouse_sk:not_integer' end,
      case when ws_promo_sk is not null and ws_promo_sk !~ '^-?\d+$' then 'ws_promo_sk:not_integer' end,
      case when ws_order_number is not null and ws_order_number !~ '^-?\d+$' then 'ws_order_number:not_integer' end,
      case when ws_quantity is not null and ws_quantity !~ '^-?\d+$' then 'ws_quantity:not_integer' end,
      case when ws_wholesale_cost is not null and ws_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'ws_wholesale_cost:not_numeric' end,
      case when ws_list_price is not null and ws_list_price !~ '^-?\d+(\.\d+)?$' then 'ws_list_price:not_numeric' end,
      case when ws_sales_price is not null and ws_sales_price !~ '^-?\d+(\.\d+)?$' then 'ws_sales_price:not_numeric' end,
      case when ws_ext_discount_amt is not null and ws_ext_discount_amt !~ '^-?\d+(\.\d+)?$' then 'ws_ext_discount_amt:not_numeric' end,
      case when ws_ext_sales_price is not null and ws_ext_sales_price !~ '^-?\d+(\.\d+)?$' then 'ws_ext_sales_price:not_numeric' end,
      case when ws_ext_wholesale_cost is not null and ws_ext_wholesale_cost !~ '^-?\d+(\.\d+)?$' then 'ws_ext_wholesale_cost:not_numeric' end,
      case when ws_ext_list_price is not null and ws_ext_list_price !~ '^-?\d+(\.\d+)?$' then 'ws_ext_list_price:not_numeric' end,
      case when ws_ext_tax is not null and ws_ext_tax !~ '^-?\d+(\.\d+)?$' then 'ws_ext_tax:not_numeric' end,
      case when ws_coupon_amt is not null and ws_coupon_amt !~ '^-?\d+(\.\d+)?$' then 'ws_coupon_amt:not_numeric' end,
      case when ws_ext_ship_cost is not null and ws_ext_ship_cost !~ '^-?\d+(\.\d+)?$' then 'ws_ext_ship_cost:not_numeric' end,
      case when ws_net_paid is not null and ws_net_paid !~ '^-?\d+(\.\d+)?$' then 'ws_net_paid:not_numeric' end,
      case when ws_net_paid_inc_tax is not null and ws_net_paid_inc_tax !~ '^-?\d+(\.\d+)?$' then 'ws_net_paid_inc_tax:not_numeric' end,
      case when ws_net_paid_inc_ship_tax is not null and ws_net_paid_inc_ship_tax !~ '^-?\d+(\.\d+)?$' then 'ws_net_paid_inc_ship_tax:not_numeric' end,
      case when ws_net_profit is not null and ws_net_profit !~ '^-?\d+(\.\d+)?$' then 'ws_net_profit:not_numeric' end
    ], null) as _anomaly_reasons
  from raw
)
select
    ws_sold_date_sk,
    ws_sold_time_sk,
    ws_ship_date_sk,
    ws_item_sk,
    ws_bill_customer_sk,
    ws_bill_cdemo_sk,
    ws_bill_hdemo_sk,
    ws_bill_addr_sk,
    ws_ship_customer_sk,
    ws_ship_cdemo_sk,
    ws_ship_hdemo_sk,
    ws_ship_addr_sk,
    ws_web_page_sk,
    ws_web_site_sk,
    ws_ship_mode_sk,
    ws_warehouse_sk,
    ws_promo_sk,
    ws_order_number,
    ws_quantity,
    ws_wholesale_cost,
    ws_list_price,
    ws_sales_price,
    ws_ext_discount_amt,
    ws_ext_sales_price,
    ws_ext_wholesale_cost,
    ws_ext_list_price,
    ws_ext_tax,
    ws_coupon_amt,
    ws_ext_ship_cost,
    ws_net_paid,
    ws_net_paid_inc_tax,
    ws_net_paid_inc_ship,
    ws_net_paid_inc_ship_tax,
    ws_net_profit,
    _anomaly_reasons as anomaly_reasons
from validated
where array_length(_anomaly_reasons, 1) >= 1
